acpica/acpica

source/include/platform/acnetbsd.h
The downstram NetBSD version for the reference:
http://cvsweb.netbsd.org/bsdweb.cgi/src/sys/external/bsd/acpica/dist/include/platform/acnetbsd.h
First test pull request for acpica.
The intention is to push all improvements upstream and reduce diff between acpica found in the NetBSD sources and current git release.
=> Upstream part of the NetBSD changes to its platform config

source/compiler/aslmapenter.c
warning: cast from function call of type 'char *' to non-matching type 'long unsigned int'
=> iASL: Add two workarounds for a very old GCC bug.

source/common/adisasm.c
Fixes a crash in case DisasmFilename can't be opened.
DisasmFilename is allocated from the string cache, it should not be
free()d.
=> Fix invalid free

source/components/executer/exutils.c, source/components/namespace/nsxfname.c, source/components/utilities/utids.c, source/include/acinterp.h, source/include/acnames.h, source/include/actypes.h, source/include/acutils.h
ACPI Device object often contains a _CLS object to supply PCI-defined class
code for the device. This patch introduces logic to process the _CLS
object. Suravee Suthikulpanit, Lv Zheng.
Acked-by: Mika Westerberg <mika.westerberg@linux.intel.com>
Reviewed-by: Hanjun Guo <hanjun.guo@linaro.org>
Signed-off-by: Suravee Suthikulpanit <Suravee.Suthikulpanit@amd.com>
Signed-off-by: Lv Zheng <lv.zheng@intel.com>
=> Utilities: Add _CLS processing

tests/aslts/bin/asltsrun
Reference: http://pubs.opengroup.org/onlinepubs/009695399/utilities/uname.html
`uname -i` and `uname -o` aren't supported on NetBSD.
=> Use portable uname option -a to unveil platform details

source/components/hardware/hwxfsleep.c, source/components/tables/tbfadt.c, source/components/tables/tbutils.c, source/components/tables/tbxfload.c, source/include/acglobal.h, source/include/aclocal.h, source/include/acpixf.h
It is reported resuming failure if we enabled 64-bit FADT addresses favor:
https://bugzilla.kernel.org/show_bug.cgi?id=74021
The root cause is:
1. Linux only supports real mode resuming
32bit waking vector address is used for real mode environment
64bit waking vector address is used for 32bit or 64bit plat memory environment
2. BIOS may still look at 32-bit FACS reported in the FADT, setting 32bit waking vector of 64-bit FACS reported in the FADT doesn't work.
The series enables 64-bit favor with the exclusion of the above 2 cases
1. For case 1, it is OSPM feature, so we update AcpiSetFirmwareWakingVector() API so that OSPM can determine the value of the both vectors
2. For case 2, we introduce a new AcpiGbl_Use32BitFacsAddresses option to exclude this case, and we load both 32bit and …
=> Acpica 64bit

source/include/platform/acefi.h, source/include/platform/acefiex.h, source/include/platform/acenvex.h, source/os_specific/service_layers/osefixf.c
This patch copies EFI interface definitions to the ACPICA code base so that
the EFI utility support can be ported to other EFI implementation.
Known issues:
1. MS Builds of uefi_call_wrapper()
The uefi_call_wrapper() in GNU EFI is implemented in a the way to work
around the ABI difference between Unix and MS. While I don't have
environment to test the MS builds.
In order to port the ACPICA utilities to other EFI implementation, all that
need to be done is to impelement the 64-bit division support and the
program entry point where the efi_main() is invoked. Code to impelement
these is platform specific, and ACPICA currently choose to hide such
platform specific code within the specific EFI impelementation. Lv Zheng.
Signed-off-by: Lv Zheng <lv.zheng@intel.com>
=> EFI: Add EFI interface definitions to eliminate dependency of GNU EFI.

generate/msvc/AcpiExec.dsp, generate/msvc/AcpiSubsystem.dsp, generate/msvc/ApiTest.dsp, generate/msvc/AslCompiler.dsp, source/components/hardware/hwxfsleep.c, source/components/tables/tbfadt.c, source/components/tables/tbinstal.c, source/components/tables/tbutils.c, source/components/tables/tbxfload.c, source/include/acglobal.h, source/include/aclocal.h, source/include/actables.h
The fixed table indexes leave holes in the global table list.
1. One hole can be seen when there is only 1 FACS provided by the BIOS.
2. Tow holes can be seen when it is a reduced hardware platform.
The holes do not break OSPMs but has broken ACPI debugger "tables"
command.
Also the fixed table indexes may make the address of the standard tables
installed earlier than DSDT to be overridden from the global table list.
This patch removes fixed table indexes and make indexes determined by the
table loaders. This can fix all above issues. Lv Zheng.
Signed-off-by: Lv Zheng <lv.zheng@intel.com>
=> Tables: Remove fixed table indexes.

generate/unix/iasl/Makefile
Support for POSIX yacc was broken since d8a0e96. This patch lets us build iasl again with it.
=> iASL: Support POSIX yacc again.

source/components/debugger/dbdisply.c, source/components/debugger/dbxface.c, source/components/dispatcher/dscontrol.c, source/components/dispatcher/dsutils.c, source/components/dispatcher/dswexec.c, source/include/acdebug.h, source/include/acmacros.h, source/include/acpixf.h
Runtime stub mechanism for debugger functions that can be invoked by the rest of the ACPICA world.
So they are interfaces exported by the debugger that can be invoked by the interpreter.
If we do not make them stubs in a correct way, we can see debugger output in the kernel logs.
Thanks
-Lv
=> Acpica debug stub

source/include/aclocal.h
Looking at where these are used, this shouldn't result in any behavioral changes, but it's best practices to have them.
=> aclocal: Put parens around some definitions.

source/compiler/aslstubs.c, source/components/events/evregion.c, source/components/hardware/hwxfsleep.c, source/components/namespace/nsinit.c, source/components/tables/tbxfload.c, source/components/utilities/utxfinit.c, source/include/acglobal.h, source/include/acnamesp.h, source/include/acpixf.h, source/tools/acpiexec/aemain.c, source/tools/examples/examples.c
It is proven that for _REV >= 2 platforms where ECDT is provided, EC._REG is not required to be invoked, this makes EmbeddedControl another early available operation region like SystemMemory/SystemIo/PciConfig that can be accessed during namespace initialization.
While other evaluations and region accesses may only happen after the namespace is initialized.
ACPI spec proposed a way to offer an ECAV method, in which, when _REV >= 2, EC accesses are allowed, otherwise, EC accesses are only allowed if EC._REG has been executed.
But many platofmrs are not implemented in this way, they set ECOK which should be set in EC._REG to indicate the availability of EC accesses in \\_SB._INI without providing ECAV.
In order not to break such platforms during the bug fixing of early operation region …
=> Acpica init

source/compiler/aslstubs.c, source/components/executer/exconfig.c, source/components/namespace/nsinit.c, source/components/tables/tbxfload.c, source/components/utilities/utxfinit.c
After validation, I can see the correct behavior is to execute entire table rather than the current behavior.
And enabling this requires many tests and fixes in Linux environment.
This is the real module level execution enabling and those required fixes detected in the Linux environment.
=> Acpica module

source/components/events/evregion.c, source/components/events/evrgnini.c, source/components/namespace/nsinit.c, source/include/acevents.h
This pull request contains required fixes for enabling "AcpiGbl_GroupModuleLevelCode = FALSE".
- _REG association issue:
In Linux, EC is supported in 2 ways:
During early stage, Linux will install EC operation region handler without _REG executed using ECDT EC settings. This allows EC read/write transactions to happen during the table loading.
During late stage, Linux will uninstall EC operation region handler and re-install EC operation region handler with _REG executed using DSDT EC settings. This allows EC read/write transactions and query event handling to happen after the table loading.
Then it seems _REG association will fail in the first step as the namespace hasn't been fully initialized at that time and the association cannot be recovered in the second step.
This patch fixes this …
=> Acpica order

generate/unix/iasl/Makefile
- byacc has a bug in "-o" option parsing.  Prefix may not be set properly
if its argument contains ".c" somewhere before the actual output file name.
With "byacc -ofoo.cXXXXX/foo.c -d foo.y", for example, it generates "foo.h"
instead of "foo.cXXXXX/foo.h" because ".cXXXXX/foo.c" is replaced with ".h".
- Prefer a GNU make built-in function, suffix(), rather than a series of
complex variable substitutions, to improve readability.
- Exit with a meaningful exit status to make it more like a real function.
=> Improve compatibility with POSIX yacc.

source/tools/acpixtract/acpixtract.c
Minor issue, Gbl_TableCount is an unsigned int, so we should be using
a %u format specifier instead of %d.
=> acpixtract: use %u format specifier on unsigned int Gbl_TableCount

source/components/namespace/nsaccess.c, source/components/utilities/utdebug.c, source/components/utilities/utdecode.c, source/include/acoutput.h, source/include/acutils.h
These changes fixes casting `const char *` to `char *` and `void *` warnings.  It is critical for FreeBSD kernel.
=> Fix deconstification warnings with '-Wcast-qual'

source/components/hardware/hwregs.c, source/include/acmacros.h
2 issues are detected by coverity unit tests.
=> Acpica access

source/os_specific/service_layers/oswintbl.c
Newer Windows versions expose SSDT tables via the registry. Make sure
that AcpiDump is able to query for these tables.
Tested with 'acpidump' and 'acpidump -s' on Windows 7 (registry entries
not present, nothing to dump), Windows 8.1 and 10 (29 SSDT tables). The
number of ACPI tables was be varied using QEMU system emulation.
Reference: https://bugs.acpica.org/show_bug.cgi?id=1282
Signed-off-by: Peter Wu <peter@lekensteyn.nl>
=> Windows: add support for dumping SSDT tables

source/compiler/aslopt.c, source/components/disassembler/dmresrcl2.c
The commas are legal but inadvisable here.
=> Use ; instead of , where appropriate.

source/include/platform/acefi.h, source/os_specific/efi/oseficlib.c
Avoid 'logical-op' warning caused by stdout and stderr (both defined as ST->ConOut).
This patch replaces the stdout and stderr defines by global variables (both initialized to point to ST->ConOut).
=> Fix efi build with gcc 6.0+

source/components/namespace/nsnames.c, source/components/namespace/nsxfname.c, source/include/acnamesp.h
BZ 1182 fix.
Fixing a lock issue in AcpiGetName().
It's just a theoretical issue, but worthy of fixing.
=> Acpica name

source/tools/acpixtract/acpixtract.c, source/tools/acpixtract/axutils.c
Users copying the output of acpidump may accidentally replace LF by
CRLF which confused acpixtract, resulting in only one line.
That happens because `\r\n` is not considered an empty line. Then
AxListTables would continue trying to read a whole header (`\r\nSSDT @
0x...`) and discover that `\r\nSS` is not a valid signature and skip to
the next line. At that point however, the header is partially read and
cannot be matched anymore.
Signed-off-by: Peter Wu <peter@lekensteyn.nl>
=> acpixtract: support CRLF in input files

source/include/platform/aclinux.h
Adds s390x as a 64-bit architecture.
=> Linux-specific header: Add support for s390x compilation.

source/components/executer/exfldio.c, source/components/hardware/hwregs.c, source/include/acmacros.h
Current GAS code in Linux upstream.
AcpiHwWrite() support is not included because of issue related to the predefined FADT register length.
However AcpiHwRead() won't be affected.
So it is tested in Linux upstream for months and is proven to be safe.
Our new GAS improvement will be based on this.
Thanks
=> Acpica gas

generate/linux/gen-patch.sh, generate/linux/gen-repo.sh
Urgent fix that fixes breakage of Linuxize process.
SHA1 hash now has conflicts preventing linuxized patches from being generated.
=> Acpica linuxize

source/components/disassembler/dmopcode.c, source/components/disassembler/dmwalk.c, source/include/acdisasm.h, source/include/aclocal.h
iasl compiles Switch/Case statements into a single iteration While
loop with If/Else statements. This patch adds support to recognize
this generated compiler output and disassemble it back to the original
Switch statement.
Signed-off-by: David E. Box <david.e.box@linux.intel.com>
=> Disassembler: Add Switch/Case disassembly support

source/compiler/aslxref.c
Since iasl cannot detect if an argument passed to a method is being
used as a reference, it is incorrect for the compiler to assume that
the argument is never used. Do not display this remark when ArgX is
being assigned a value.
Link: https://bugs.acpica.org/show_bug.cgi?id=1332
Suggested-by: Jeffrey Hugo <jhugo@codeaurora.org>
Signed-off-by: David E. Box <david.e.box@linux.intel.com>
=> Compiler: Remove "Argument never used" remark if ArgX is a Target

generate/unix/Makefile.common
The HARDWARE_NAME variable is only used to display some messages saying
whether a 32-bit or a 64-bit build was done, which is pretty
useless. This commit gets rid of this variable entirely.
Signed-off-by: Thomas Petazzoni thomas.petazzoni@free-electrons.com
=> generate/unix/Makefile.common: remove HARDWARE_NAME

source/components/debugger/dbmethod.c
On the error return path when AcpiGetObjectInfo fails the allocated
pathname is not free'd leading to a memory leak.  Free pathname
to fix this.
=> debugger: fix memory leak on Pathname

source/common/dmextern.c, source/compiler/aslcompile.c, source/compiler/aslglobal.h, source/compiler/asloptions.c, source/components/disassembler/dmopcode.c, source/components/disassembler/dmwalk.c, source/include/acdisasm.h
This patch adds an ACPICA testing feature that allows external
opcodes to be generated in place. This switch (-oE) doesn't place
an If (0) block around the opcodes. Use of this functions is for
compiler/disassembler testing only and is not intended to be
run through the interpreter. When this switch is used, the
disassembler will output the externals in the same location they
were at in the original ASL code and will not generate a separate
list of externals at the top of the file.
Signed-off-by: David E. Box <david.e.box@linux.intel.com>
=> compiler: disassembler: compile and disassemble externals in place

source/components/disassembler/dmopcode.c, source/include/aclocal.h
Change the Switch disassembly code to check if the conversion can be
done earlier before removing temporary (_T_x) names. Prevents invalid
disassembly of AML created by older compilers (circa 2005).
Link: https://bugs.acpica.org/show_bug.cgi?id=1358
Link: https://bugs.acpica.org/show_bug.cgi?id=1360
Reported-by: racerrehabman@gmail.com
Signed-off-by: David E. Box <david.e.box@linux.intel.com>
=> Disassembler: Do not unconditionally remove temporary names

source/compiler/asltypes.h
This works around an unnecessary redefinition of typedef `YY_BUFFER_STATE`.
=> Remove redefinition of YY_BUFFER_STATE.

source/include/aclocal.h
`FILE` is only defined in user land via `stdio.h`.
=> Fix build for FreeBSD kernel.

generate/unix/Makefile.config
This is to facilitate compiling ACPICA tools as 32-bit programs on 64-bit machines.
To build as 32 bit programs, set the M32 variable to true when running make
Example: make M32=TRUE
Note: if the above results in a compilation error, there is a possibility
that 32-bit libraries may not be installed. If this is the case, run the
following command (on Ubuntu compiling with gcc)
sudo apt-get install g++-multilib libc6-dev-i386
and run make again.
=> Makefile: enable compilation of ACPICA tools as 32-bit programs

source/common/adwalk.c, source/components/disassembler/dmwalk.c, source/components/dispatcher/dswload.c, source/include/aclocal.h
All instances using a named parseOp's path field has a type
cast from UINT8* to char*. Changing path's type from UINT8*
to char* eliminates type casting and retains the previous
behavior.
=> Change path's type from UINT8* to char*

source/tools/acpisrc/asremove.c, source/tools/acpisrc/astable.c
Fix a segfault when acpisrc is used for undetectable simple union/struct typedefs.
=> Acpica typedef

tests/aslts/Makefile.def
This pull request aids the binary comparison sequence (compile-disassemble-recompile-binary compare) within ASLTS so that the initial compilation and disassembly retain externals in place, rather than moving the externals to the top of the definition block and alphabetizing their order.
=> Aslts external op

source/components/utilities/utownerid.c
The runtime errors caused when acpica tools are compiled with
-fsanitize=shift imply that these 1s are stored in integers.
This cast insures that 1 is stored in unsigned integers.
=> Explicitly cast 1 to UINT32.

source/include/platform/acgcc.h, source/include/platform/acintel.h
Facilities to allow excluding gcc's stdarg.h.
Tested in efi builds by adding -DACPI_USE_BUILTIN_STDARG in Makefiles.
=> Acpica gcc

source/compiler/aslsupport.l, source/compiler/cvdisasm.c
This solves the issue with /* comments appearing in place of // comments within listing files and fixes generation of include statements.
=> iasl: only convert // comments to /* during conversion

source/compiler/aslload.c, tests/aslts/src/runtime/cntl/ehandle.asl
This pull request changes the compiler behavior when there are externals and named objects with the same name. If these externals and named objects appear in different definition blocks, the externals are references to the named object. This case is considered a valid use case and passes compilation. If these externals and named objects appear in the same definition block, this is considered a redefinition of that named object or external and results in an error. With this new change in behavior, the external(_ERR, MethodObj) declaration in ehandle.asl within ASLTS has to be deleted to avoid redefinition of _ERR.
=> External op refactor02

source/common/dmtbdump.c
The assignment to Length is redundant as the stored value is
overwritten again before it is read. Issue detected by
CoverityScan CID#163885 ("Unused Value")
=> dmtbdump: remove redundant assigment to Length

source/common/dmextern.c
=> disassembler: use memmove instead of malloc/free to move data

source/compiler/aslload.c, source/components/namespace/nsaccess.c, source/include/aclocal.h, tests/aslts/src/runtime/collections/functional/external/MAIN.asl
This change resolves bz1389 and allows compilation of code like the following:
`DefinitionBlock (...)`
`{`
`    External (ABCD.EFGH)`
`    Device (ABCD) {Name (IJLK,0)}`
`}`
=> Iasl external fix01

source/include/actbl2.h
IORT revision C has been published with a number of new SMMU
implementation identifiers; define them.
Signed-off-by: Robin Murphy <robin.murphy@arm.com>
=> IORT: Update SMMU models for revision C

source/components/hardware/hwxfsleep.c, source/include/platform/acenv.h, source/include/platform/aclinux.h
The Linux kernel is going to soon be using a gcc plugin for automatically
randomizing structure layouts of structures that are entirely function
pointers. To support this, initializers need to use designated
initialization rather than ordered initialization. This provides a macro,
ACPI_STRUCT_INIT, to handle both cases, keeping ordered initialization
for non-Linux builds.
=> Optionally use designated initializers for function pointers

source/components/executer/exfield.c
Detected on the Surface 3:
The MSHW0011 driver uses Field Attrib Raw Process to return information
for the ACPI Battery. The DSDT declares a parameter of 2 though
functions like _BST or _BIX require a much bigger out buffer.
It looks like the incoming buffer has the requested size and we can
work around the issue by using this input size as the output and
parameters size.
As metioned by Stephen Just on the kernel bugzilla (comment 44):
"Lv, after reading through 5.5.2.4.5.3 of the ACPI spec several times,
it appears that AccessLength is ignored for AttribRawProcessBytes
accesses - the access length is always specified by the user - and
in fact, the example omits the AccessLength argument entirely.
More specifically, comparing 5.5.2.4.5.3.9 and 5.5.2.4.5.3.10, it
appears that the only …
=> Executer: adapt buffer length for Field Attrib Raw Process in Ops Region

source/components/executer/excreate.c
The following ACPI table contains an invalid target node within the
Alias operator:
```
DefinitionBlock ("", "SSDT", 1, "Bug", "BugTable", 0x00001000)
{
Scope (_SB)
{
Device (DEV0)
{
Name (_ADR, 1)
Device (DEV1)
{
Alias (_ADR, _ADR)
}
}
}
}
```
If an ACPI table contains such an invalid target node in an Alias
operator, a segmentation fault will occur when the target node is
dereferenced within AcpiExCreateAlias. Add a check for such an invalid
target node in AcpiExCreateAlias.
Signed-off-by: Alex James <theracermaster@gmail.com>
=> iASL: Ensure that the target node is valid in AcpiExCreateAlias

source/compiler/aslload.c, source/components/parser/psobject.c
this pull request resolves bz1397 by skipping incorrect external declarations in the AML during disassembly. Also, this pull request fixes field unit compilation so that iasl emits an error when there is a field unit declaration and an external declaration of the same in a definition block.
=> Iasl external fix02

source/components/utilities/utresrc.c
This reverts commit c8eac10178b387f9eb1935694e509d4518da77bb resolves bz1391 and improves ASLTS results by decreasing failures and incrementing passes by 6.
=> Revert "Update resource descriptor handling"

source/common/dmtbinfo.c, source/include/actbl2.h
ARM IORT specification has provision to define Proximity domain
in SMMUv3 IORT table. Adding required changes to decode
Proximity domain of SMMUv3 IORT table.
Signed-off-by: Ganapatrao Kulkarni <ganapatrao.kulkarni@cavium.com>
=> iasl: Update to IORT SMMUv3 disassembling

source/components/hardware/hwregs.c, source/components/utilities/utresrc.c, source/include/actypes.h
ACPICA 201700629 release materials.
No significant divergences can be seen except 2 small changes. They are there because Linux side merged 2 urgent fixes and thus the fixes were not in ACPICA upstream.
This series back ports the ACPICA parts of the 2 commits.
=> Acpica 1706

source/compiler/aslcompile.c, source/compiler/aslcompiler.h, source/compiler/aslerror.c, source/compiler/aslglobal.h, source/compiler/aslhelp.c, source/compiler/aslmessages.c, source/compiler/aslmessages.h, source/compiler/asloptions.c, source/compiler/asltypes.h, source/compiler/dtutils.c
The -vx [messageId] option, where the x stands for EXpect, allows the
compiler to expect that the compilation will result in an ASL exception
with a particular messageId. If this error is not raised. The
compilation will result in an error. This will help create a whole new
class of compilation tests in ASLTS.
=> iASL: add option to expect specific compilation remarks/warnings/errors

generate/unix/Makefile.config
Add OPT_LDFLAGS to be specified during compilation for custom linker
flags. Disable optimization (adding -O0) when NOOPT is set to true.
Signed-off-by: Alex James <theracermaster@gmail.com>
=> Unix makefiles: Add OPT_LDFLAGS and edit NOOPT parsing

source/components/tables/tbxface.c, source/tools/acpiexec/aetables.c
My local test code for the new deferred table verification mechanism. I enhanced it so that it could be upstreamed.
This commit is not urgent but it will nicer to have it in the upstream as:
1. The enhanced sanity check in AcpiReallocateRootTable() makes the condition of the check a necessary and sufficient condition.
2. OSPMs now can freely change the allocation style of the global root table list while still be able to enable the deferred table verification feature when AcpiReallocateRootTable() is invoked.
=> Acpiexec test

tests/aslts/src/runtime/collections/exceptions/exc/exc.asl
The ACPI spec's definition of implicit conversion does not allow
'0x' within strings that are converted to integers. Without '0x'
the number being converted could be mistaken as a decimal number.
Instead we are allowing with 0x or no 0x and both versions are
implicitly converted to hex.
=> ASLTS: exc: allow implicit conversion of strings with "0x" to hex

tests/aslts/Makefile.def, tests/aslts/bin/Do, tests/aslts/bin/asltsrun
This is a convenient feature that will print the path of ./Do 2 output if mismatched results exist.
=> Add functionality to invoke Do 2 if previous test run does not match the current test run results

source/components/parser/psobject.c
resolves [bz1397](https://bugs.acpica.org/show_bug.cgi?id=1397)
=> disassembler: reset ParserState's Aml pointer when parsing bad external declarations

source/components/hardware/hwtimer.c
Delta calculation has an off-by-one error when there is a rollover.
For example, when StartTicks is 0x00FFFFFF and EndTicks is 0x00000000
(for 24-bit timer), DeltaTicks should be 1 (one) but it was 0 (zero).
=> Fix an off-by-one error in AcpiGetTimerDuration().

source/compiler/aslcompiler.h, source/compiler/aslerror.c, source/compiler/aslload.c, source/compiler/aslmessages.c, source/compiler/aslmessages.h, source/compiler/asltypes.h
This pull request adds AslDualParseOpError, a function that takes two parse nodes and two messages so that more detailed error messages can be emitted. For example, the following error message indicates the location of multiple declarations by using multiple parse nodes:
```
DSDT.iiii   1692:       Device(PEG2) {
Error    6074 -                  ^ Name already exists in scope (PEG2)
Original name creation/declaration below:
DSDT.iiii     93:   External(\_SB.PCI0.PEG2, DeviceObj)
```
=> iASL: adding support for more detailed compiler errors

source/components/parser/psutils.c
The calls to AcpiOsAcquireObject can result in a null being assigned
to Op (for example if a mutex acquire fails) which can lead to a
null pointer dereference on Op on the call to ASL_CV_TRANSFER_COMMENTS
(via function CvTransferComments).  Move the block into the previous
block that checks for a null Op so that we never can call
CvTransferComments with a null Op.
Detected by: CoverityScan CID#1371660 ("Dereference after null check")
=> Avoid null pointer dereference on Op.

source/os_specific/efi/osefixf.c
The function name in the documentation of AcpiEfiCompareGuid was referring to the wrong function.
=> Fix function name in documentation

source/compiler/cvparser.c
CommentOption is being initialized and then this value is being
overwritten by a subsequent assignment to CommentOption, hence the
first setting of CommentOption is redundant and can be removed. Cleans
up clang warning:
Value stored to 'CommentOption' during its initialization is never read
=> iASL: remove redundant initialization of CommentOption

source/compiler/aslload.c, source/components/namespace/nsaccess.c, source/components/namespace/nssearch.c
The declaration External (ABCD.EFGH) creates two nodes in the namespace: ABCD
and EFGH where ABCD is marked as an implicit external node. ABCD is labeled as
implicit because there does not exist a specific External (ABCD) declaration.
Before this change, the declaration External (ABCD.EFGH) and
External (ABCD.EFGH.IJKL) creates the namespace nodes ABCD, EFGH, and IJKL
where ABCD and EFGH are labeled as implicit external nodes. This is incorrect.
The only implicit node should be ABCD because EFGH and IJKL are explicit nodes.
This change fixes the labeling procecess of external op namespace nodes so that
nodes are properly labeled as implicit external.
Due to this commit, the below ASL code results in a compilation error.
DefinitionBlock ("DSDT.aml", "DSDT", 0x02, "INTEL", "BDW     ", 0x0) …
=> iASL: change processing of external op namespace nodes for correctness

tests/aslts.sh, tests/aslts/HOW_TO_INSTALL, tests/aslts/HOW_TO_USE, tests/aslts/bin/Do
Recent versions of ASLTS now use the acpibin utility, much like they
use acpiexec.  However, when use of acpibin was added, it was not
treated like acpiexec and was assumed to exist in whatever PATH a user
had set when running the tests.  When trying to use ASLTS in a very
pristine environment (i.e., no previous version of ACPICA user space
tools is available), portions of the test suite will produce false
failures because acpibin cannot be found and run.
This patch fixes ASLTS so that the use of acpibin is treated exactly
the same as acpiexec -- an environment variable must be defined (in
this case, $acpibin) with the location of the executable, aslts.sh
makes sure a value for the variable is set, Do uses $acpibin (instead
of assuming acpibin exists in a user's PATH), and the various …
=> ASLTS: provide proper PATH for acpibin in tests

source/components/events/evgpe.c, source/components/events/evgpeblk.c, source/components/events/evxface.c, source/components/events/evxfgpe.c, source/components/hardware/hwgpe.c, source/components/hardware/hwsleep.c, source/components/hardware/hwxfsleep.c, source/include/acevents.h, source/include/actypes.h
This patchset can help to avoid all kinds of GPE losses:
1. Gpe shouldn't be cleared which may cause GPE loss, but should be handled.
2. Edge-triggered GPE should be polled once right after being enabled.
However in order for GPE handler to be safe for both IRQ context and task context, GPE handling should be parallelized - achieved via per-GPE bit handling.
=> Acpica Gpe

source/include/actbl1.h
Fix spelling mistake, "Reseved" -> "Reserved"
=> Trivial fix to spelling mistake in comment

source/components/utilities/uttrack.c, source/tools/acpiexec/aemain.c, tests/aslts/bin/asltsrun
This fixes Acpiexec and ASLTS so that memory statistics are emitted to the output of ASLTS.
=> ASLTS: fix memory statistics

source/components/namespace/nsnames.c
=> Namespace: fix memory leak from building prefixed pathname

source/include/actbl1.h
The ACPI 6.2 spec has flags to describe cache
allocation, write back, and whether
it is an instruction, data or unified cache.
Signed-off-by: Jeremy Linton <jeremy.linton@arm.com>
=> ACPI 6.2: Additional PPTT flags

source/compiler/aslsupport.l
`yytext[]` should never be tested against `EOF` because `lex(1)` cannot
produce `yytext` containing `EOF`.  In fact, `(yytext[i] != EOF)` is always
true on those platforms because `EOF` is defined as an implementation
specific *negative* integer by the ANSI C, often times defined as `-1`.
Specifically for the above expression, `yytext[i]` is implicitly promoted
to a signed integer before comparison and it can never be a negative
value because `sizeof int` is greater than `sizeof char`.
=> Fix build on a platform where char is unsigned.

source/components/utilities/utdebug.c
The %*s format specifier prints a string with a width indicated by an integer
In the case of AcpiOsPrintf ("%*s", AcpiGbl_NestingLevel, " "), a single space
is printed to the console when AcpiGbl_NestingLevel is 0 or 1. This change
increments AcpiGbl_NestingLevel so that there is one space printed when
AcpiGbl_NestingLevel is 0 and two spaces printed when AcpiGbl_NestingLevel is 1.
=> Debugger: fix slight indentation issue

source/components/utilities/utosi.c, source/include/actypes.h
The [public Microsoft document](http://download.microsoft.com/download/7/e/7/7e7662cf-cbea-470b-a97e-ce7ce0d98dc2/winacpi_osi.docx) listing recognized Windows OSI strings shows that these two strings were introduced in recent versions.
- version 1607 / Anniversary Update / "Redstone 1"
- version 1703 / Creators Update / "Redstone 2"
=> Recognize the Windows 10 version 1607 and 1703 OSI strings

source/components/executer/exdump.c
This adds a semi-colon at the end of a macro call so that it can be processed
correctly with source code formatting tools.
=> trivial style fix, no functional change

source/compiler/asloptions.c
The -da option consumes the next argument incorrectly. This
change prevents -da from consuming additional arguments.
=> iASL: do not get additional arguments for -d or -da options

source/include/platform/aclinux.h
X32 follows ILP32 model. Check for ILP32 as well when checking for
x86_64 to ensure the defines are correct for X32 ABI.
Signed-off-by: Anuj Mittal <anuj.mittal@intel.com>
=> Linux: add support for X32 ABI compilation

source/include/actypes.h
This fixes compiler warnings about NULL pointer arithmetic, e.g., -Wnull-pointer-arithmetic for Clang 6.  We cannot assume NULL is always (void *)0 because C language standard clearly says NULL is an implementation-defined macro.  Clang 6 complains about this by default.
=> Clean up macros related to pointer arithmetic

source/compiler/aslerror.c, source/compiler/aslload.c, source/compiler/aslmessages.c, source/compiler/aslmessages.h
This fix is a temporary adjustment to lower redundant externals
from an error to a warning.
=> iASL: drop external name collision to a warning for now

source/components/utilities/utosi.c, source/include/actypes.h
Dell uses this string to activate Thunderbolt native mode on supported
machines.
This is necessary to support the work that was done in the Linux kernel for native mode:
https://marc.info/?l=linux-acpi&m=151853954129169&w=2
=> Recognize the _OSI string "Windows 2017.2"

source/components/events/evgpeblk.c, source/components/parser/psobject.c, source/components/tables/tbinstal.c, source/include/acmacros.h
This fix also involves putting some ACPI_ERROR_NAMESPACE parameters inside
macros. By doing so, we avoid compilation errors from unused variables.
=> macros: fix ACPI_ERROR_NAMESPACE macro

source/components/namespace/nseval.c
I found an ACPI cache leak in ACPI early termination and boot continuing case.
When early termination occurs due to malicious ACPI table, Linux kernel
terminates ACPI function and continues to boot process. While kernel terminates
ACPI function, kmem_cache_destroy() reports Acpi-Operand cache leak.
Boot log of ACPI operand cache leak is as follows:
>[    0.464168] ACPI: Added _OSI(Module Device)
>[    0.467022] ACPI: Added _OSI(Processor Device)
>[    0.469376] ACPI: Added _OSI(3.0 _SCP Extensions)
>[    0.471647] ACPI: Added _OSI(Processor Aggregator Device)
>[    0.477997] ACPI Error: Null stack entry at ffff880215c0aad8 (20170303/exresop-174)
>[    0.482706] ACPI Exception: AE_AML_INTERNAL, While resolving operands for [OpcodeName unavailable] (20170303/dswexec-461)
>[    0.487503] …
=> acpi: acpica: fix acpi operand cache leak in nseval.c

tests/aslts/bin/asltsrun, tests/aslts/bin/common
This change adds parallelization of ASLTS execution via xargs. This
results in a performance gain of 2.3x (14m 22sec to 6m 7sec).
Various functions and variables are exported so that they can be used
in each run_test_case execution.
=> ASLTS: parallelize ASLTS acpiexec execution for speed

source/components/events/evevent.c
This ensures that AcpiEvFixedEventDetect does not use FixedStatus and
and FixedEnable as uninitialized variables.
=> Events: add a return on failure from AcpiHwRegisterRead

source/components/debugger/dbdisply.c, source/components/namespace/nsdumpdv.c, source/components/namespace/nsxfname.c, source/include/actypes.h
As the documentatuon above its declaration indicates, AcpiGetObjectInfo()
is intended for early probe usage and as such should not call any methods
which may rely on OpRegions, before this commit it was also calling _STA,
which on some systems does rely on OpRegions.
Calling _STA before things are ready leads to errors such as these
(under Linux, on some hardware):
[    0.123579] ACPI Error: No handler for Region [ECRM] (00000000ba9edc4c)
[GenericSerialBus] (20170831/evregion-166)
[    0.123601] ACPI Error: Region GenericSerialBus (ID=9) has no handler
(20170831/exfldio-299)
[    0.123618] ACPI Error: Method parse/execution failed
\_SB.I2C1.BAT1._STA, AE_NOT_EXIST (20170831/psparse-550)
End 2015 support for the _SUB method was removed for exactly the same
reason. Removing CurrentStatus …
=> Remove calling of _STA from AcpiGetObjectInfo()

source/tools/acpisrc/asfile.c
=> acpisrc: restore check to avoid segfault on modes other than -l

source/components/tables/tbinstal.c
The spelling of "sucessfully" should be "successfully", fix this
=> Tables: Fix spelling mistake in comment

source/components/resources/rsdump.c
There is a potential infinite loop if AcpiRsDumpByteList is
called with a Length greater than 255 since the current loop
counter is just a UINT8 and will wrap to zero and never reach
the desired value in Length.  Fix this by making the loop
counter the size type as Length.
=> Fix potential infinite loop in AcpiRsDumpByteList

source/components/utilities/utprint.c
gcc 7 is unhappy about this fallthrough.
=> acpi: this statement may fall through

source/common/acfileio.c
The table header validation was intended for AML tables rather than
data tables. This caused an error when disassembling tables with
unusual table signatures such as the RSDP table.
=> disassembler: remove incorrect table header validation for data tables

source/components/parser/psloop.c, source/components/parser/psobject.c, source/components/utilities/uterror.c
This change alters the parser so that the table load does not abort
upon an error.
Notable changes:
If there is an error while parsing an element of the termlist, we
will skip parsing the current termlist element and continue parsing
to the next opcode in the termlist.
If we get an error while parsing the conditional of If/Else/While or
the device name of Scope, we will skip the body of the statement all
together.
If we get an error while parsing the base offset and length of an
operation region declaration, we will remove the operation region
from the namespace.
=> AML parser: attempt to continue loading table after error

source/common/dmextern.c, source/compiler/aslglobal.h, source/compiler/asloptions.c
There are some functions that attempt to store 2 String buffers in
MsgBuffer. This causes compiler warnings due to potential overflow
of MsgBuffer.
By increasing the MsgBuffer, we retain current behavior for functions
using StringBuffer. This also results in separating the size between
MsgBuffer and StringBuffer.
=> iASL: increase the length of MsgBuffer to avoid overflow

source/components/hardware/hwsleep.c
After commit 18996f2db918 (ACPICA: Events: Stop unconditionally
clearing ACPI IRQs during suspend/resume) the status of ACPI events
is not cleared any more when entering the ACPI S5 system state (power
off) which causes some systems to power up immediately after turing
off power in certain situations.
That is a functional regression, so address it by making the code
clear the status of all ACPI events again when entering S5 (for
system-wide suspend or hibernation the clearing of the status of all
events is not desirable, as it might cause the kernel to miss wakeup
events sometimes).
Fixes: 18996f2db918 (ACPICA: Events: Stop unconditionally clearing ACPI IRQs during suspend/resume)
Reported-by: Takashi Iwai <tiwai@suse.de>
Tested-by: Thomas Hänig <haenig@cosifan.de>
Cc: 4.17+ …
=> ACPICA: Clear status of all events when entering S5

source/components/hardware/hwregs.c
Reported-by: Mark Gross <mark.gross@intel.com>
=> ACPICA: add status check for AcpiHwRead before assigning return value

source/components/utilities/uterror.c
Commit 5088814a6e93 (ACPICA: AML parser: attempt to continue loading table
after error) unintentionally added leading newlines to error messages emitted by
ACPICA which caused unexpected things to be printed to the kernel log.  Drop
these newlines (which effectively reverts the part of commit 5088814a6e93
adding them).
Fixes: 5088814a6e93 (ACPICA: AML parser: attempt to continue loading table
after error)
Reported-by: Toralf Förster <toralf.foerster@gmx.de>
Reported-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>
=> ACPICA: Drop leading newlines from error messages

source/components/utilities/utstrsuppt.c, source/components/utilities/utstrtoul64.c, source/include/acutils.h
AcpiUtImplicitStrtoul64 called AcpiUtDetectHexPrefix and ignored the
return value. Instead, use AcpiUtRemoveHexPrefix.
=> Utilities: split hex detection into smaller functions

source/components/parser/psloop.c
This change skips the entire length of opcodes that open a scope
(Device, Scope, Processor, etc) if the creation of the op fails. The
failure could be caused by various errors including AE_ALREADY_EXISTS
and AE_NOT_FOUND.
Reported-by: Jeremy Linton <jeremy.linton@arm.com>
Tested-by: Jeremy Linton <jeremy.linton@arm.com>
=> AML Parser: skip opcodes that open a scope upon parse failure

source/components/dispatcher/dsfield.c, source/components/namespace/nsaccess.c, source/include/aclocal.h, source/include/acnamesp.h, source/tools/acpiexec/aecommon.h, source/tools/acpiexec/aeinitfile.c, source/tools/acpiexec/aemain.c
Field elements listed in the init file used to be initialized after
the table load and before executing module-level code blocks. The
recent changes in module-level code means that the table load becomes
a method execution. If fields are used within module-level code and
we are executing with -fi option, then these values are populated
after the table has finished loading. This commit changes the
initialization of objects listed in the init file so that field unit
values are populated during the table load.
=> AcpiExec: fixing -fi option

source/include/acconfig.h
Reviewed-by: Dimitri Sivanich <dimitri.sivanich@hpe.com>
Tested-by: Russ Anderson <russ.anderson@hpe.com>
Reported-by: Mike Travis <mike.travis@hpe.com>
=> Reference Counts: increase max to 0x4000 for large servers

source/compiler/aslcompile.c, source/compiler/aslerror.c, source/compiler/aslmain.c, source/compiler/aslpredef.c, source/tools/acpidump/apmain.c, source/tools/acpiexec/aemain.c
… is defined
When building ACPICA in the Linux kernel with Clang with ACPI_DISASSEMBLER
not defined we get a the following warning on variable DisplayOp:
warning: variable 'display_op' set but not used [-Wunused-but-set-variable]
Fix this warning by guarding the declaration of DisplayOp with some
ACPI_DISASSEMBLER #ifdefs
=> Use %d for signed int print formatting instead of %u 

source/components/debugger/dbxface.c
When building ACPICA in the Linux kernel with Clang with ACPI_DISASSEMBLER
not defined we get a the following warning on variable DisplayOp:
warning: variable 'display_op' set but not used [-Wunused-but-set-variable]
Fix this by refactoring DisplayOp and ParentOp code in a separate function.
Suggested-by: Signed-off-by: Colin Ian King <colin.king@canonical.com>
=> Debugger: refactor to fix unused variable warning

source/compiler/dtio.c
Without this check there is a bounds violation that occurs when
DtTrim attempts to remove a double quote charater later in the
function. The End gets set to 1 byte before Start.
Suggested-by: Steven Noonan
=> iASL: add additional check for strings with length zero

source/compiler/dtio.c
If the '\\' is next to a "\r\n", it is also a continuation
=> iASL: properly detect continuation on dos files

source/components/utilities/utosi.c, source/include/actypes.h
"Windows 2018.2" was added for Windows 10, version 1809.
https://docs.microsoft.com/en-us/windows-hardware/drivers/acpi/winacpi-osi
=> Add "Windows 2018.2" string in the _OSI support

source/components/dispatcher/dsobject.c, source/components/dispatcher/dsutils.c, source/components/dispatcher/dswload.c, source/components/dispatcher/dswload2.c, source/components/dispatcher/dswstate.c, source/components/executer/excreate.c, source/components/executer/exutils.c, source/components/namespace/nsload.c, source/components/parser/psloop.c, source/components/utilities/utglobal.c, source/include/acglobal.h
=> Remove defines that use deprecated ACPI_NO_METHOD_EXECUTE flag

source/components/executer/exserial.c
This is a back-port of Hans de Goede's patch.
Generic Serial Bus transfers use a data struct like this:
struct gsb_buffer {
u8      status;
u8      len;
u8      data[0];
};
acpi_ex_write_data_to_field() copies the data which is to be written from
the source-buffer to a temp-buffer. This is done because the OpReg-handler
overwrites the status field and some transfers do a write + read-back.
Commit f99b89eefeb6 ("ACPICA: Update for generic_serial_bus and
attrib_raw_process_bytes protocol") acpi_ex_write_data_to_field()
introduces a number of problems with this:
1) It drops a "length += 2" statement used to calculate the temp-buffer
size causing the temp-buffer to only be 1/2 bytes large for byte/word
transfers while it should be 3/4 bytes (taking the status and len field
into account). This …
=> ACPICA: Fix handling of buffer-size in acpi_ex_write_data_to_field()

source/components/events/evrgnini.c, source/components/namespace/nsparse.c, source/components/parser/psloop.c, source/components/tables/tbxfload.c, source/include/acpixf.h, source/tools/acpiexec/aemain.c, source/tools/acpinames/anmain.c
Module-level code refers to executable ASL code that runs during
table load. This is typically used in ASL to declare named objects
based on a condition evaluated during table load like so:
DefinitionBlock(...)
{
OpreationRegion (OPR1, SystemMemory, ...)
Field (OPR1)
{
FLD1, 8 /* Assume that FLD1's value is 0x1 */
}
/* The if statement below is referred to as module-level code */
If (FLD1)
{
/* Declare DEV1 conditionally */
Device (DEV1) {...}
}
Device (DEV2)
{
...
}
}
In legacy module-level code, the execution of the If statement
was deferred after other modules were loaded. The order of
code execution for the table above is the following:
1.) Load OPR1 to the ACPI Namespace
2.) Load FLD1 to the ACPI Namespace (not intended for drivers)
3.) Load DEV2 to the ACPI Namespace
4.) Execute If …
=> Remove legacy module-level code support

source/compiler/aslcompiler.l
I was looking at the lexer and had to think about this for a few minutes to realize what this part of the code base was doing. I added a short explanation
=> iASL: add explanation for nameseg lexing, no functional change

source/components/utilities/utdecode.c
There is a missing comma between strings on the array declaration. Fix
this by adding the missing comma.
Fixes: 205ac8fc7210 ("ACPI 6.3: add Error Disconnect Recover Notification value")
=> utdecode: fix missing comma in array declaration AcpiGbl_GenericNotify

source/components/utilities/utdecode.c
=> utilities: fix spelling of PCC to PlatformCommChannel

source/compiler/aslerror.c
=> iASL: fix ww option by using the correct variable to index the array

source/include/platform/aclinux.h
=> Linux: use different debug default than ACPICA

source/components/events/evgpe.c
Commit 18996f2db918 ("ACPICA: Events: Stop unconditionally
clearing ACPI IRQs during suspend/resume") was added to stop clearing
of event status bits unconditionally on suspend and resume paths. This
was done because of an issue
reported (https://bugzilla.kernel.org/show_bug.cgi?id=196249) where
lid status stays closed even on resume (which happens because event
status bits are cleared unconditionally on resume). Though this change
fixed the issue on suspend path, it introduced regressions on several
resume paths.
First regression was reported and fixed on S5 path by the following
change: commit fa85015c0d95 ("ACPICA: Clear status of all events when
entering S5"). Next regression was reported and fixed on all legacy
sleep paths by the commit f317c7dc12b7 ("ACPICA: Clear status of all …
=> Events: Clear status of an event before enabling it

source/compiler/aslcompiler.h, source/compiler/aslerror.c, source/compiler/aslfiles.c
This reverts commit 1eb3ee94b6ab2e231a5f7cdf7ca6388ff886c031.
=> Revert "iASL: use .src file handle only for include file error messages"

source/compiler/aslcompile.c, source/compiler/aslmain.c, source/compiler/aslutils.c
This option only does preprocessing. No need to perform static
analysis.
=> iASL: do not perform static analysis with -P option

source/compiler/aslstartup.c
=> iASL: stop clearing error log after parsing each file

source/components/events/evgpe.c
This reverts ACPICA commit 6c43e1acdf93a04ca32898d1d89d93fde04d121a.
Revert "ACPICA: Clear status of GPEs before enabling them"
Revert commit c8b1917c8987 ("ACPICA: Clear status of GPEs before
enabling them") that causes problems with Thunderbolt controllers
to occur if a dock device is connected at init time (the xhci_hcd
and thunderbolt modules crash which prevents peripherals connected
through them from working).
Commit c8b1917c8987 effectively causes commit ecc1165b8b74 ("ACPICA:
Dispatch active GPEs at init time") to get undone, so the problem
addressed by commit ecc1165b8b74 appears again as a result of it.
Fixes: c8b1917c8987 ("ACPICA: Clear status of GPEs before enabling them")
Link: https://lore.kernel.org/lkml/s5hy33siofw.wl-tiwai@suse.de/T/#u
Link: …
=> Revert "Events: Clear status of an event before enabling it"

source/compiler/aslload.c, source/compiler/aslmessages.c, source/compiler/aslxref.c
This reverts commit 3132320003b348bcf48274d4e326e496ffc4b23b.
This commit unintentionally emitted AML bytecode with incorrect
package lengths for some ASL code related to Fields and
OperationRegions. This mal-formed AML can cause systems to crash
during boot.
=> Revert "iASL: Additional forward reference detection (illegal)"

source/include/platform/aclinux.h
This flag should not be included in #ifndef CONFIG_ACPI. It should be
used unconditionally.
=> Linux: move ACPI_DEBUG_DEFAULT flag out of ifndef

source/compiler/asldefine.h, source/compiler/aslglobal.h, source/compiler/aslload.c, source/compiler/aslmessages.c, source/compiler/aslmessages.h
_WAK and _PTS in any other scope will not be invoked by OS.
=> iASL: ensure that _WAK and _PTS are declared only at the root scope

source/compiler/aslload.c
By definition, Index field should be based off of Field units rather
than Operation Regions.
=> iASL: fix type mismatch on IndexField

source/components/events/evgpe.c, source/components/events/evgpeblk.c, source/components/events/evxface.c, source/components/events/evxfgpe.c, source/include/acevents.h
ACPI GPEs (other than the EC one) can be enabled in two situations.
First, the GPEs with existing _Lxx and _Exx methods are enabled
implicitly by ACPICA during system initialization.  Second, the GPEs
without these methods (like GPEs listed by _PRW objects for wakeup
devices) need to be enabled directly by the code that is going to use
them (e.g. ACPI power management or device drivers).
In the former case, if the status of a given GPE is set to start
with, its handler method (either _Lxx or _Exx) needs to be invoked to
take care of the events (possibly) signaled before the GPE was
enabled. In the latter case, however, the first caller of
acpi_enable_gpe() for a given GPE should not be expected to care
about any events that might be signaled through it earlier.  In that
case, it is better …
=> ACPICA: Clear status of GPEs on first direct enable

source/components/debugger/dbobject.c
Pointer ObjDesc is being initialized with a value that is never
read and it is being updated later with a new value. The initialization
is redundant and can be removed.
Addresses-Coverity: ("Unused value")
=> Debugger: remove redundant assignment on ObjDesc

source/components/executer/exconfig.c
This prevents re-acquiring the interpreter lock when loading tables
=> Table load: exit interpreter before initializing objects

source/compiler/aslcompile.c, source/compiler/aslcompiler.h, source/compiler/aslmain.c
=> iASL: return -1 if AML files were not generated due to compiler errors

source/compiler/aslload.c, source/compiler/aslmessages.c, source/compiler/aslmessages.h
_UID under a processor object must evaluate to an integer rather than
a string.
=> iASL: emit error when _UID under a processor object is a string

source/components/dispatcher/dsmethod.c
This line was added unintentionally in commit db2638cca.
=> Remove unintentional call to delete walkstate

source/compiler/aslmessages.c, source/compiler/aslmessages.h, source/compiler/asltransform.c
The ASL Processor() object has been deprecated in ACPI 6.0
=> iASL: add warning on legacy ASL Processor() keyword

source/compiler/aslmain.c, source/compiler/asltypes.h, source/compiler/aslutils.c, source/compiler/dtcompile.c
When compiling multiple tables, the global file node struct is used
to keep statistics for each input file. This change adds support for
using global file nodes to keep track of statistics for each data
table including total line conut, total field count, errors detected
during parsing.
=> iASL: fix compile-time statistics for data table compiler

source/compiler/dtcompile.c, source/compiler/dtcompilerparser.l
This adds support for /* ... */ and // comments, uses AcpiUtSafeStrncpy instead of strcpy in the lexer, and fixes compile-time statistics for the data table compiler
=> Data table enhancements

tests/aslts.sh, tests/templates/Makefile
For each template supported by iASL, this test suite does the
following:
1) Compile with iASL
2) Disassemble .aml file generated from 1)
3) Re-compile .dsl file generated from 2)
4) Use acpibin to compare files generated from 1) and 3) using
acpibin
This test exercises the data table compiler as well as the data table
disassembler.
=> ASLTS: add iASL template test suite

source/components/utilities/utosi.c, source/include/actypes.h
This adds Windows 10 1903 release to _OSI support.
https://docs.microsoft.com/en-us/windows-hardware/drivers/acpi/winacpi-osi
https://github.com/MicrosoftDocs/windows-driver-docs/commit/881e49865d833a6e0f582162fa2731ec48b05c70
Note the code name is 19H1.
https://en.wikipedia.org/wiki/Windows_10_version_history#Version_1903_(May_2019_Update)
https://blogs.windows.com/windowsexperience/2018/07/25/announcing-windows-10-insider-preview-build-17723-and-build-18204
=>  Add "Windows 2019" string to _OSI support.

source/include/platform/acfreebsd.h
This lets us detect lock order reversal in ACPICA code to avoid deadlock.
https://github.com/freebsd/freebsd/commit/3d1ee970f47db4dfd60b30b0e64539bbf4c26d0f
=> FreeBSD: Enable ACPICA mutex debugging in INVARIANTS case.

source/compiler/dtcompilerparser.l, source/compiler/dtcompilerparser.y
=> iASL: DT: eliminate %code directive, it is not POSIX compliant

source/compiler/dtcompile.c
At this point in the program, assume that *(Field)->Name is non-null
because the data table parser will emit an error on fields that do
not contain data. Info->Name can only be NULL when Info is a
ACPI_DMT_TERMINATOR which does not set the DT_OPTIONAL flag.
This change will revert the table compiler to the previous behavior
by creating an instance of a subtable struct for empty subtables such
as VRTC and MTMR data tables.
=> iASL: remove unnecessary null checks

source/compiler/aslkeywords.y
This should use the ACPI_NUM_PREDEFINED_REGIONS macro instead of a
magic number.
=> iASL: fix custom address space range check

source/components/debugger/dbfileio.c, source/components/tables/tbxfload.c, source/include/acpixf.h, source/tools/acpiexec/aetests.c
For unloading an ACPI table, it is necessary to provide the index of
the table. The method intended for dynamically loading or hotplug
addition of tables, AcpiLoadTable(), should provide this information
via an optional pointer to the loaded table index.
This patch fixes the table unload function of acpi_configfs.
Reported-by: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
Fixes: d06c47e3dd07f ("ACPI: configfs: Resolve objects on host-directed
table loads")
Signed-off-by: Nikolaus Voss <nikolaus.voss@loewensteinmedical.de>
=> make acpi_load_table() return table index

source/components/debugger/dbinput.c, source/components/debugger/dbnames.c, source/components/utilities/utbuffer.c, source/include/acdebug.h, source/include/acstruct.h, source/include/acutils.h
This command dumps the name segment and values contained within field units of a particular operation region subtype.
=> acpiexec: add fields command

source/common/dmtbdump2.c
The disassembly of the optional padding field resulted in dumping
the remainder of the length in the subtable. This is problematic
when there are mappings that are describes after the padding field.
The length of the mappings are a part of the subtable length. When
dumping the optional padding field, the mapping length should be
subtracted from the rest of the field so that the proper length of
padding should be dumped.
=> Disassembler: IORT: fix output of optional padding field

source/components/dispatcher/dsfield.c
The ObjDesc reference count should only be removed if we get an
actual reference to the object.
=> dispatcher: fix reference count removal

source/compiler/dttable2.c
The error return path is not free'ing previously allocated
resource LocalityBuffer and hence there is a memory leak. Fix this
by free'ing it before returning.
Fixes: c22c0b1df98c ("Data table compiler: Add error messages for SLIT locality buffers")
=> iASL: fix memory leak of LocalityBuffer on error return path

source/components/debugger/dbinput.c
There is a spelling mistake in an error message. Fix it.
=> debugger: fix spelling mistake "adress" -> "address"

source/compiler/aslerror.c, source/compiler/aslfiles.c, source/compiler/aslstartup.c, source/compiler/aslutils.c, source/compiler/dtcompile.c
In iASL, not being able to find the internal representation of an
input file is an unrecoverable condition. Instead of returning NULL
for this case, it's better to simply abort iASL instead of continuing
the compilation.
Reported-by: Colin Ian King <colin.king@canonical.com>
=> iASL: abort with an error when current file is not found

source/compiler/aslcompile.c
This change fixes the opcode walk and the transformation walk to only
traverse the parse tree after the entire parse tree has been formed.
parse tree. Walking the entire tree any earlier would require repeated
calls to walk the parse tree and results in longer execution time.
=> iASL: move opcode walk and transformation

source/common/dmtables.c, source/components/dispatcher/dsfield.c, source/components/dispatcher/dswload.c
CreateBufferField is a deferred op that is typically processed in
load pass 2. However, disassembly of control method contents walk the
parse tree with ACPI_PARSE_LOAD_PASS1 and AML_CREATE operators are
processed in a later walk. This is a problem when there is a control
method that has the same name as the AML_CREATE object. In this case,
any use of the name segment will be detected as a method call rather
than a reference to a buffer field. If this is detected as a method
call, it can result in a mal-formed parse tree if the control methods
have parameters.
This change in processing AML_CREATE ops earlier solves this issue by
inserting the named object in the ACPI namespace so that references
to this name would be detected as a name string rather than a method
call.
Reported-by: Elia …
=> Disassembler: create buffer fields in ACPI_PARSE_LOAD_PASS1

source/common/dmtables.c
By setting the integer width, the disassembler no longer trucates 64-
bit integers in AML tables with revision 2 or higher.
Reported-by: Elia Geretto <elia.f.geretto@gmail.com>
Tested-by: Elia Geretto <elia.f.geretto@gmail.com>
=> Disassembler: set integer width for AML indicated by the table revision

source/compiler/asldefine.h, source/compiler/aslload.c, source/compiler/aslxref.c
As of now, iASL does not keep track of parameter counts for external
declarations of methods. In order to determine the parameter count of
external control methods, iASL looks at the first method and saves
the parameter count in AML. However, this information is not present
during namespace cross reference.
This allows code like this to compile without errors:
DefinitionBlock ("", "DSDT", 2, "", "", 0x01)
{
External (DS01, MethodObj)
DS01(0x2,0x2) // DS01 is called with 2 parameters
DS01()        // DS01 is called with 0 parameters
}
This change saves the parameter count of the first method call and
uses it to analyze subsequent method calls. This ensure that a method
that is declared external is called with the same amount of
parameters each time.
Signed-off-by: Erik Schmauss …
=> iASL: save parameter count of external control method calls for analysis

source/compiler/aslfiles.c, source/compiler/dtcompile.c
They are unneeded because these functions do not return NULL. In the
case that these functions fail, they end up aborting the entire
program rather than returning NULL.
Reported-by: Colin Ian King <colin.king@canonical.com>
=> iASL: remove unneeded NULL checks

source/compiler/aslload.c
=> iASL: emit error on duplicate named objects rather than a warning

source/compiler/aslcompile.c, source/compiler/aslerror.c
=> iASL: switch to the correct file during error node creation

source/compiler/aslload.c
Fixes forward reference analysis for field declarations by searching
the parent scope for the named object when the object is not present
in the current scope.
=> iASL: fix forward reference analysis for field declarations

source/compiler/aslerror.c
Previous implementation did not print the extra message inside
suberror nodes. This change prints the extra message (if it exists).
=> iASL: print extra message inside of suberror nodes

source/compiler/aslrules.y
The ASL grammar allows methods to be declared with a list of
parameter types. Each parameter type can have a list of optional
types.
For example the following method declaration returns an integer and
has 3 parameters: Arg0 is a string type, Arg1 is either integer or
string, and Arg2 is an integer.
Method (EXAM, 2, NotSerialized, 3, IntObj, {StrObj, {IntObj, StrObj}, IntObj})
{
// Code here....
}
Previously, the parse tree that represented the parameter list
contained a list of types without any information on alternate types
such as Arg1 in the above example. In other words, the parse tree of
the parameter type list in the above method declaration looked like
this:
StrObj -> IntObj -> StrObj -> IntObj
In order to signify that Arg1 is supposed to be either an integer or
string, this …
=> iASL: nest optional parameter types inside a default arg node

source/common/adisasm.c, source/common/dmtables.c, source/compiler/cvparser.c, source/include/acconvert.h, source/include/acmacros.h
Error messages generated by the AML parser during disassembly are
emitted to the output file. This is a problem because these messages
do not belong as a part of the output file. If these messages are
emitted in the output file, the user must first delete these messages
before the .dsl file can be re-compiled.
This change refactors existing code and moves the call to redirect
AcpiOsPrintf() after the AML parser has built the parse tree to fix
this problem.
=> Prevent disassembler from spilling error messages to output file

source/compiler/aslexternal.c, source/compiler/aslmessages.c, source/compiler/aslmessages.h
=> iASL: prevent return types and parameter types in non-method externals

generate/efi/Makefile.common, generate/efi/Makefile.config, generate/unix/Makefile.config, generate/unix/acpidump/Makefile, generate/unix/acpiexec/Makefile
Some machines may be using HOST in their environment to represent the
host name for their machines. Avoid this problem by renaming to
ACPI_HOST.
=> ACPICA: Makefile: replace HOST with ACPI_HOST

source/components/hardware/hwsleep.c
Hibernation (S4) is triggered in a guest when it recieves a sleep
trigger from the hypervisor. When the guest resumes from this power
state, it does not see the SleepEnabled bit. In otherwords, the sleep
button is not enabled on waking from an S4 state. This causes
subsequent invocation of sleep state to fail in the guest.
Fix this problem by enabling the sleep button in ACPI legacy wake.
Signed-off-by: Anchal Agarwal <anchalag@amazon.com>
Reviewed-by: Balbir Singh <sblbir@amazon.com>
Reviewed-by: Frank van der Linden <fllinden@amazon.com>
[ ek: changelog]
=> Enable sleep button on ACPI legacy wake

source/compiler/aslmethod.c
Previous commit broke parameter counting for methods that declared
the argument count but omitted the parameterType list.
=> iASL: fix method parameter counting when parameterType list is omitted

source/compiler/aslcompiler.h, source/compiler/aslmethod.c, source/compiler/aslxref.c
=> iASL: use correct macro name for error message and other trivial fixes

source/compiler/aslcompiler.h, source/compiler/aslexternal.c, source/compiler/aslmethod.c, source/compiler/aslutils.c, source/compiler/aslxref.c
This pull request fixes logic to use ACPI_BTYPE instead of ACPI_TYPE. This pull request also moves functions intended to get objects that represent the parent method to aslutils.c and renames them.
=> Iasl trivial fixes and code movement

source/compiler/aslmethod.c
At this point, some named objects may not have a namespace node and
cause the compiler to crash. Instead of using the namespace node to
find the NameSeg, this change uses the parse object's NameSeg
field.
=> iASL: use Op->Asl.Nameseg to prevent segfault during method analysis

source/components/namespace/nsnames.c, source/components/namespace/nsxfname.c
When compiling ACPICA with VS2019 x64 with some size conversion related warnings set to errors (namely C4244 and C4267) compilation aborts. The affected locations are fixed with this pull request.
=> Size casts

source/components/events/evxfgpe.c, source/components/hardware/hwgpe.c, source/include/achware.h, source/include/acpixf.h
Introduce a new helper function, AcpiAnyGpeStatusSet(), for
checking the status bits of all enabled GPEs in one go.
It is needed to distinguish spurious SCIs from genuine ones when
deciding whether or not to wake up the system from suspend-to-idle.
Signed-off-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>
=> Introduce AcpiAnyGpeStatusSet ()

source/compiler/aslcompiler.l, source/components/utilities/utdecode.c, tests/aslts/src/runtime/collections/functional/region/regionfield.asl
The former was proposed during specification discussions but it was
dropped. This keyword was introduced to the ACPICA code base by
mistake so this commit changes the keyword representing Platform
Communication Channel to be PCC.
=> Change PlatformCommChannel ASL keyword to PCC

source/compiler/aslload.c
This pull request contains a fix for type checking external declarations against actual named object declaration and removes a useless iASL error.
=> iASL: fix analysis of External declarations

source/components/utilities/utprint.c
On 32-bit, the provided sprintf() is non-functional: with a size of
ACPI_UINT32_MAX, String + Size will wrap, meaning End < Start, and
AcpiUtBoundStringOutput() will never output anything as a result.
The symptom we saw of this was acpixtract failing to output anything.
Signed-off-by: John Levon <john.levon@joyent.com>
=> utilities: fix sprintf()

source/tools/acpibin/abcompare.c
The local variable Buffer is shadowing another variable called
Buffer that also declared in the same source file. Avoid any accidental
name shadowing confusion by renaming the local variable. Cleans up
cppcheck static analysis warning:
source/tools/acpibin/abcompare.c:622:30: style: Local variable 'Buffer'
shadows outer variable [shadowVariable]
char                    *Buffer = NULL;
source/tools/acpibin/abcompare.c:159:29: note: Shadowed declaration
char                        Buffer[BUFFER_SIZE];
source/tools/acpibin/abcompare.c:622:30: note: Shadow variable
char                    *Buffer = NULL;
=> acpibin: rename Buffer to DataBuffer to avoid name shadowing

source/common/ahtable.c, source/common/dmtbinfo3.c, source/include/actbl3.h
The table signature WSMT stands for "Windows SMM Mitigations Table".
It is not "Windows SMM Migrations Table".
Reported-by: Laszlo Ersek <lersek@redhat.com>
=> WSMT: Fix typo, no functional change

source/include/actbl2.h
NHLT (Non-HDAudio Link Table) provides configuration of audio
endpoints for Intel SST (Smart Sound Technology) DSP products.
iASL data table compiler support will be implemented in the near
future.
[EK: edited commit message]
Signed-off-by: Cezary Rojewski <cezary.rojewski@intel.com>
=> Add NHLT table signature

source/tools/acpixtract/acpixtract.h
This macro needs to be surrounded by parens. Otherwise, a logical
statement that applies a logical not operator to this macros could
result in a computation that applies the operator to the left side of
the logical and but not the right.
Reported-by: John Levon <john.levon@joyent.com>
=> acpixtract: fix AX_IS_TABLE_BLOCK_HEADER macro

source/compiler/aslload.c
The type mismatch of externals rarely result in an ACPI runtime
error so drop these to a warning for now.
=> iASL: drop type mismatch of externals from error to warning

source/common/acgetline.c, source/components/debugger/dbhistry.c, source/include/acglobal.h
This commit cleans up the code by moving the global definition out of
a .c file to a more approperiate acglobal.h file.
Reported-by: Hulk Robot <hulkci@huawei.com>
Suggested-by: Jason Yan <yanaijie@huawei.com>
=> Move AcpiGbl_NextCmdNum definition to acglobal.h

source/components/executer/exfield.c
A linux-based static analyzer (sparse) caught this as a warning.
Making this variable static will result in better optimizations and
ensure that this variable does not get used outside of this file.
Signed-off-by: Yue Haibing <yuehaibing@huawei.com>
[ek: commit message]
=> Make AcpiProtocolLengths static

source/common/dmtbdump2.c
Some compilers catch potential uninitialized variables. This is done
by examining branches of if/else statements. This change replaces an
"else if" with an "else" to fix the uninitialized variable warning.
=> IVRS table: fix potentially uninitialized variable warning

source/include/acpredef.h
Previously, there was a mixup where _NIG required one parameter and
_NIH required zero parameters. This changes swaps these parameter
requirements. Now this change requires _NIH to be called with one
parameter and _NIG requires zero.
=> fix required parameters for _NIG and _NIH

source/compiler/aslload.c
This fixes a regression that occurred in the following commit:
e47525c99de25a95861abdf9184e8424b7ea5d67
iASL: fix incorrect type override of namespace nodes during namespace load
The previous commit unintentionally removed the code to insert
external method parameter count.
=> iASL: fix insertion of external method parameter count

source/compiler/aslmessages.c, source/compiler/aslmessages.h, source/compiler/aslxref.c
This pull request allows the following code to compile under multiple table
compilation:
External (ABCD)
if (CondRefOf (ABCD))
{
ABCD = 0
}
The above code snippet does not result in any ACPI runtime errors
because the assignment of ABCD is guarded by the if statement.
=> iASL: allow protected access of unresolved externals

source/compiler/aslxref.c
Some AML interpreter implementations do not search the parent scope
during the execution of the CondRefOf operator. They require
pathnames with parent prefixes (^) or full namestrings. This change
prevents the namepath optimization that results from cross-
referencing the CondRefOf parameter introduced in commit 9091f8909
(iASL: cross-reference namestring parameter of CondRefOf operator).
=> iASL: do not optimize namepaths under CondRefOf operator

source/components/utilities/utids.c, source/include/actypes.h
The current codebase makes use of one-element arrays in the following
form:
struct something {
int length;
u8 data[1];
};
struct something *instance;
instance = kmalloc(sizeof(*instance) + size, GFP_KERNEL);
instance->length = size;
memcpy(instance->data, source, size);
but the preferred mechanism to declare variable-length types such as
these ones is a flexible array member[1][2], introduced in C99:
struct foo {
int stuff;
struct boo array[];
};
By making use of the mechanism above, we will get a compiler warning
in case the flexible array does not occur last in the structure,
which will help us prevent some kind of undefined behavior bugs from
being inadvertently introduced[3] to the linux codebase from now on.
This issue was found with the help of Coccinelle and audited _manually_.
[1] …
=> Replace one-element array with flexible-array

tests/aslts/src/runtime/collections/bdemo/ACPICA/0239_ACTION_REQUIRED/MAIN.asl, tests/aslts/src/runtime/collections/bdemo/ACPICA/0240_ACTION_REQUIRED/MAIN.asl, tests/aslts/src/runtime/collections/mt/mutex/MAIN.asl, tests/aslts/src/runtime/collections/mt/mutex/SPEC, tests/aslts/src/runtime/collections/mt/mutex/common.asl, tests/aslts/src/runtime/collections/mt/mutex/mt_access.asl, tests/aslts/src/runtime/collections/mt/mutex/mutex.asl, tests/aslts/src/runtime/collections/mt/mutex/mxs.asl, tests/aslts/src/runtime/collections/mt/mutex/service.asl, tests/aslts/src/runtime/collections/mt/mutex/tests.asl, tests/aslts/src/runtime/collections/mt/mutex/worker_thr.asl
The tests/ subdirectory contains confusing (and offensive) language
that is not tied to any "external" specifications. The thread worker
naming convention is more accurately named "Worker". (The controlling
thread was already named "Controller".) Rename one file and update the
language throughout.
This removes 209 instances, leaving only the 67 that are tied to
specification language.
For background and further details on the technical and societal
rationale for these changes, please see:
https://tools.ietf.org/id/draft-knodel-terminology-01.html
Signed-off-by: Kees Cook <kees@outflux.net>
=> ASLTS: Replace inaccurate language

source/compiler/aslerror.c
The loop counter i is a U16 where as the upper bound is a UINT32 which
in theory could lead to an infinite loop if AslGbl_ElevatedMessagesIndex
is greater than 65535.  In practice this is probably never going to
occur, but make code fully safe by making the loop counter a UINT32.
Addresses-Coverity: ("Infinite loop")
=> iASL: clean up loop counter mismatch with upper bound

source/components/executer/exprep.c, source/components/utilities/utdelete.c
Object reference counts are used as a part of ACPICA's garbage
collection mechanism. This mechanism keeps track of references to
heap-allocated structures such as the ACPI operand objects.
Recent server firmware has revealed that this reference count can
overflow on large servers that declare many field units under the
same OperationRegion. This occurs because each field unit declaration
will add a reference count to the source OperationRegion.
This change solves the reference count overflow for OperationRegions
objects by preventing fieldunits from incrementing their
OperationRegion's reference count. Each OperationRegion's reference
count will not be changed by named objects declared under the Field
operator. During namespace deletion, the OperationRegion namespace
node will be deleted …
=> Do not increment OperationRegion reference counts for field units

source/include/platform/aclinux.h
Add 64 bit risc-v architecture.  Useful for acpica tools and
incorporating ACPICA into the Firmware Test Suite.
=> Add support for 64 bit risc-v compilation.

source/common/dmtbinfo1.c, source/include/actbl1.h
- rename Processor to Attached Initiator
- drop deprecated bits from Memory Proximity Domain flag
- bump ACPI version in HMAT comment
Signed-off-by: Michal Biesek <michal.biesek@intel.com>
=> ACPI 6.3: HMAT updates

source/include/actbl1.h
Update System Locality Latency and Bandwidth Information Flags possible
values: remove "Last level memory" and update rest of values
Signed-off-by: michalbiesek <michal.biesek@intel.com>
=> ACPI 6.3: Remove last level memory cache

source/compiler/aslmessages.c, source/compiler/aslmessages.h, source/compiler/aslxref.c
This change will print the line of the external declaration that was
used when iASL generated the error. In addition, this change prints
the full namepath of the object that was declared external.
=> iASL: add more details to External resolution error message

documents/changes.txt, source/compiler/aslbtypes.c, source/compiler/aslcodegen.c, source/include/accommon.h
There are several ocurrances of "the the", remove the extraneous
"the".
=> Remove extreaneous "the" in comments and changes.txt

source/components/events/evregion.c
Before this commit AcpiEvExecuteRegMethods() had special handling
to handle "orphan" (no matching OpRegion declared) _REG methods for EC
nodes.
On Intel Cherry Trail devices there are 2 possible ACPI OpRegions for
accessing GPIOs. The standard GeneralPurposeIo OpRegion and the Cherry
Trail specific UserDefined 0x9X OpRegions.
Having 2 different types of OpRegions leads to potential issues with
checks for OpRegion availability, or in other words checks if _REG has
been called for the OpRegion which the ACPI code wants to use.
Except for the "orphan" EC handling, ACPICA core does not call _REG on
an ACPI node which does not define an OpRegion matching the type being
registered; and the reference design DSDT, from which most Cherry Trail
DSDTs are derived, does not define GeneralPurposeIo, …
=> Also handle "orphan" _REG methods for GPIO OpRegions

source/components/namespace/nspredef.c, source/components/namespace/nsprepkg.c, source/components/namespace/nsrepair2.c
There was a memory leak that ocurred when a _CID object is defined as
a package containing string objects. When _CID is checked for any
possible repairs, it calls a helper function to repair _HID (because
_CID basically contains multiple _HID entries).
The _HID repair function assumes that string objects are standalone
objects that are not contained inside of any packages. The _HID
repair function replaces the string object with a brand new object
and attempts to delete the old object by decrementing the reference
count of the old object. Strings inside of packages have a reference
count of 2 so the _HID repair function leaves this object in a
dangling state and causes a memory leak.
Instead of allocating a brand new object and removing the old object,
use the existing object when …
=> Interpreter: fix memory leak by using use existing buffer in _HID repair

source/compiler/aslerror.c, source/compiler/aslwalks.c, source/compiler/dtfield.c, source/components/disassembler/dmwalk.c, source/components/dispatcher/dscontrol.c, source/components/dispatcher/dswexec.c, source/components/dispatcher/dswload.c, source/components/dispatcher/dswload2.c, source/components/executer/exfldio.c, source/components/executer/exresop.c, source/components/executer/exstore.c, source/components/hardware/hwgpe.c, source/components/utilities/utdelete.c, source/include/actypes.h, source/include/platform/acgcc.h, source/tools/acpibin/abmain.c, source/tools/acpihelp/ahdecode.c
GCC 7.1 gained -Wimplicit-fallthrough to warn on implicit fallthrough,
as well as __attribute__((__fallthrough__)) and comments to explicitly
denote that cases of fallthrough were intentional. Clang also supports
this warning and statement attribute, but not the comment form.
Robert Moore provides additional context about the lint comments being
removed. They were for "an old version of PC-Lint, which we don't use
anymore." Drop those.
This will help us enable -Wimplicit-fallthrough throughout the Linux
kernel.
Suggested-by: Robert Moore <robert.moore@intel.com>
Signed-off-by: Nick Desaulniers <ndesaulniers@google.com>
=> ACPICA: fix -Wfallthrough

source/components/debugger/dbobject.c, source/components/dispatcher/dsdebug.c, source/components/parser/psloop.c, source/components/parser/psparse.c, source/include/acexcep.h
Fixes exception code class checks in `acexcep.h`.
Currently, the exception code class check macros are broken. For example, `ACPI_ENV_EXCEPTION(Status)` will always evaluate to zero, whereas `ACPI_AML_EXCEPTION(Status)` will evaluate to non-zero for `AE_CODE_PROGRAMMER`, `AE_CODE_ACPI_TABLES`, as well as `AE_CODE_AML`. The other macros have similar problems.
This issue likely has not been detected before as these classification macros do currently not see much use.
The first commit in this PR fixes those macros, the second commit cleans up existing checks of the form `((Status & AE_CODE_MAKS) == <class>)` by replacing them with the corresponding `ACPI_<class>_EXCEPTION(Status)` macro.
=> Fix exception code class checks

source/compiler/aslanalyze.c, source/compiler/aslmethod.c
This pull request adds improvement to method call analysis by saving the btype in the parse node and relaxing certain cases of type checking
=> improve method call analysis

source/common/cmfsize.c
This module is 'cmfsize', not 'cfsize'.
Fix it.
Signed-off-by: Christophe JAILLET <christophe.jaillet@wanadoo.fr>
=> Common: Fix a typo

source/compiler/aslexternal.c
This pull request contains fixes for github issue 659 by changing iASL behavior to keep external methods that are referenced in iASL constructs such as ```if (CondRefOf (EXT0))```
=> Fix for github issue 659

source/components/events/evhandler.c, source/components/events/evregion.c, source/components/events/evxfregn.c, source/include/acobject.h
The handling of the GenericSerialBus (I2C) and GPIO OpRegions in AcpiEvAddressSpaceDispatch() passes a number of extra parameters to the address-space handler through the address-space Context pointer (instead of using more function parameters).
The Context is shared between threads, so if multiple threads try to call the handler for the same address-space at the same time, then a second thread could change the parameters of a first thread while the handler is running for the first thread.
An example of this race hitting is the Lenovo Yoga Tablet2 1015L, where there are both AttribBytes accesses and AttribByte accesses to the same address-space. The AttribBytes access stores the number of bytes to transfer in Context->AccessLength. Where as for the AttribByte access the number of bytes to …
=> Generic serial bus race fix

source/compiler/aslopcodes.c
There is a typo in a comment, fix it.
=> iASL: fix typo in comment, 3st -> 3rd

source/compiler/aslexternal.c
This reverts commit 52a82369950b8a728c40e58ccd1f026298563b7a, reversing
changes made to 79acf21c5d667214aa94ad645ba2f68e0c2c536c.
This pull request was intended to resolve a bug in the compiler but
further exposed a different bug in the compiler. Revert the material
from this pull request for now in order to diagnost the issue. It would
be nice to come up with solutions that simplify the logic in iASL's
external analysis.
=> Revert "Merge pull request #663 from SchmErik/ghi-659"

source/tools/acpisrc/astable.c
I just realized while writing the Linux support that I forgot one identifier, causing build failure after conversion to Linux headers. Sorry about that, I hope it's not too late for this release.
=> acpisrc: Add missing conversion for VIOT support

source/include/actbl2.h
ACPI_PPTT_CACHE_ID_VALID is misspeled. Fix it.
Signed-off-by: Elyes HAOUAS <ehaouas@noos.fr>
=> Fix misspeled ACPI_PPTT_CACHE_ID_VALID

source/compiler/aslerror.c
There are a couple of spelling mistakes, fix them.
=> iASL: fix typo in error message, erro -> error

source/components/namespace/nsaccess.c
ACPI is allocating an object using kmalloc(), but then frees it
using kmem_cache_free(<"Acpi-Namespace" kmem_cache>).
This is wrong and can lead to boot failures manifesting like this:
hpet0: 3 comparators, 64-bit 100.000000 MHz counter
clocksource: Switched to clocksource tsc-early
BUG: unable to handle page fault for address: 000000003ffe0018
#PF: supervisor read access in kernel mode
#PF: error_code(0x0000) - not-present page
PGD 0 P4D 0
Oops: 0000 [#1] SMP PTI
CPU: 0 PID: 1 Comm: swapper/0 Not tainted 5.6.0+ #211
Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS
Ubuntu-1.8.2-1ubuntu1 04/01/2014
RIP: 0010:kmem_cache_alloc+0x70/0x1d0
Code: 00 00 4c 8b 45 00 65 49 8b 50 08 65 4c 03 05 6f cc e7 7e 4d 8b
20 4d 85 e4 0f 84 3d 01 00 00 8b 45 20 48 8b 7d 00 48 8d 4a 01 <49> 8b
1c 04 …
=> ACPICA: Always create namespace nodes using AcpiNsCreateNode()

source/components/resources/rscalc.c
This fixes an issue found when building in 32-bit mode
Suggested-by: Robert Moore <robert.moore@intel.com>
=> Use ACPI_FORMAT_UINT64 when printing ACPI_SIZE

source/compiler/aslerror.c
The for-loop is using a UINT8 counter and comparing the upper
limit against a UINT32 AslGbl_ExpectedMessagesIndex maximum. In
the case where AslGbl_ExpectedMessagesIndex is > 255 the counter i
will wrap around to zero and the loop will never exit. I suspect
the AslGbl_ExpectedMessagesIndex is never that high, but fixing
this does future proof the code and cleans up static analysis
warnings.
Addresses-Coverity: ("Infinite loop")
=> Fix potential infinite loop due to type mismatch

source/components/namespace/nsrepair2.c
According to the ACPI spec, _CID returns a package containing
hardware ID's. Each element of an ASL package contains a reference
count from the parent package as well as the element itself.
Name (TEST, Package() {
"String object" // this package element has a reference count of 2
})
A memory leak was caused in the _CID repair function because it did
not decrement the reference count created by the package. Fix the
memory leak by calling AcpiUtRemoveReference on _CID package elements
that represent a hardware ID (_HID).
Tested-by: Shawn Guo <shawn.guo@linaro.org>
=> Fix memory leak caused by _CID repair function

source/components/utilities/utprint.c
Replace /* FALLTHROUGH */ comment with ACPI_FALLTHROUGH
Signed-off-by: Wei Ming Chen <jj251510319013@gmail.com>
=> Use ACPI_FALLTHROUGH

source/include/acbuffer.h
The ACPI specification v6.3 defines the panel positions in chapter 6.1.8
"_PLD (Physical Location of Device)"
Signed-off-by: Fabian Wüthrich <me@fabwu.ch>
Reviewed-by: Daniel Scally <djrscally@gmail.com>
Reviewed-by: Andy Shevchenko <andy.shevchenko@gmail.com>
=> Add _PLD panel positions

source/compiler/aslmessages.c
A recent commit added a new literal string to the AslTableCompilerMsgs[]
array but the previous string is missing a comma and so the two strings
are ending up being concatenated. Fix this by adding the missing comma.
Addresses-Coverity: ("Missing comma in a string array initialization")
Fixes: 81eb9c383e6d ("iASL: Add support for the BDAT ACPI table")
=> iASL: Fix a missing comma between two literal strings

source/components/utilities/utdelete.c
Fixes: c9e011695 ("Fix race in GenericSerialBus (I2C) and GPIO OpRegion parameter handling")
Reported-by: John Garry <john.garry@huawei.com>
Reported-by: Xiang Chen <chenxiang66@hisilicon.com>
Tested-by: Xiang Chen <chenxiang66@hisilicon.com>
=> Clean up context mutex during object deletion

source/common/dmtable.c
=> Disassembler: add missing strings to decode subtable types

source/include/actbl2.h, source/tools/acpisrc/astable.c
This structure is used in to parse PRMT in other Operating Systems
that relies on using subtable headers in order to parse ACPI tables.
Although the PRMT doesn't have "subtables" it has a list of module
information structures that act as subtables.
=> Add PRMT module header to facilitate parsing

source/include/actbl1.h
The Microsoft Debug Port Table 2 (DBG2) specification revision
September 21, 2020 comprises additional Serial Port Subtypes [1].
[1] https://docs.microsoft.com/en-us/windows-hardware/drivers/bringup/acpi-debug-port-table
=> Headers: Add new DBG2 Serial Port Subtypes

source/compiler/preprocess.h
=> preprocess.h: fix spelling mistake in comment

source/include/actbl2.h
This was introduced starting with ACPI 6.3.
=> Add the flag for online capable in the MADT

source/common/dmtable.c, source/common/dmtbdump3.c, source/common/dmtbinfo3.c, source/compiler/dttable2.c, source/include/acdisasm.h, source/include/actbl3.h
Add a new subtable type for SRAT Generic Port Affinity.
It uses the same subtable structure as the existing Generic
Initiator Affinity type.
Signed-off-by: Alison Schofield <alison.schofield@intel.com>
=> FOR ACPICA: ACPI 6.4 SRAT: add Generic Port Affinity type

source/include/actypes.h
This is an upstream ACPICA version of the following Linux kernel patch from Arnd Bergmann:
https://patchwork.kernel.org/project/linux-acpi/patch/20210927121338.938994-1-arnd@kernel.org/
Please consider merging.
=> Headers: Avoid NULL pointer arithmetic

source/components/hardware/hwesleep.c, source/components/hardware/hwsleep.c, source/components/hardware/hwxfsleep.c, source/include/acglobal.h
This is an upstream ACPICA version of the Linux kernel patch at
https://patchwork.kernel.org/project/linux-acpi/patch/2618833.mvXUDI8C0e@kreacher/
Please consider for merging.
=> Hardware: Avoid evaluating methods too early during system resume

source/components/hardware/hwsleep.c
This fixes a typo in a variable name introduced by one of the earlier changes.
=> Hardware: Fix typo in variable name in AcpiHwLegacyWakePrep ()

source/compiler/aslcache.c
Despite the documentation talking of strings, and the various constants and variables used in the function also doing so, UtLocalCacheCalloc gets used for things other than strings, such as FlInitOneFile using it to allocate an ASL_GLOBAL_FILE_NODE. The easiest way to fix that for a bump the pointer allocator is to just round up every allocation's size; there are more complex alternatives, as allocations smaller than the maximum native alignment only need to be rounded up to the next power of two, but optimising for that case seems unnecessarily complicated.
It might make sense to split this into a string allocator and a separate generic object allocator (to complement the existing specific object allocators) to ensure strings can still be packed tightly in memory, but that is a more …
=> iASL: Fix unaligned accesses to local cache allocations

source/components/hardware/hwesleep.c, source/components/hardware/hwsleep.c, source/components/hardware/hwxfsleep.c
This is based on the Linux kernel patch at:
https://patchwork.kernel.org/project/linux-acpi/patch/20211206122952.74139-2-kirill.shutemov@linux.intel.com/
=> Hardware: Do not flush CPU cache when entering S4 and S5

source/components/events/evregion.c, source/components/executer/exfield.c, source/include/actypes.h
Hi,
The first change is based on the fact that no one has reported any usage of PCC type 1/2 opregion,
One of the platform I use has PCC type 3 Opregion and is currently crashing at boot with log as in the commit.
So it needs to fixed ASAP.
=> Pcc opregion support

source/components/executer/exoparg1.c
This fixes the attached object reference counting error reported by Lenny Szubowicz <lszubowi@redhat.com> in pull request #685.
=> Executer: Fix the REFCLASS_REFOF case in AcpiExOpcode_1A_0T_1R ()

source/components/utilities/utdelete.c
This fixes the issue related to object reference counting reported by Mark Asselstine <mark.asselstine@windriver.com> in pull request #652.
=> Utilities: Avoid deleting the same object twice in a row

source/include/actbl2.h
The byte length of the Data field in the AEST Processor generic resource
substructure defined in ACPI for the Armv8 RAS Extensions 1.1 is 4Byte.
However, it is defined as a pointer type, and on a 64-bit machine,
it is interpreted as 8 bytes. Therefore, it is changed from a pointer
type unsigned integer 1 byte to an unsigned integer 4 bytes.
Signed-off-by: Shuuichirou Ishii <ishii.shuuichir@fujitsu.com>
=> Fix AEST Processor generic resource substructure data field byte length

source/common/dmtable.c, source/components/tables/tbprint.c
Since the Signature member is accessed through an ACPI_TABLE_HEADER, the pointer to it is only to a 4-char array, and so trying to read past the 4th character, as will be done when it is an RSDP, reads beyond the bounds of the accessed member. On CHERI, and thus Arm's experimental Morello prototype architecture, pointers are represented as capabilities, which are unforgeable bounded pointers, providing always-on fine-grained spatial memory safety. By default, subobject bounds enforcement is not enabled, only bounds on allocations, but it is enabled in the CheriBSD (a port of FreeBSD) kernel as intra-object overflow attacks are common on operating system kernels, and so this overflow is detected there and traps.
=> Avoid subobject buffer overflow when validating RSDP signature

source/include/actypes.h
The current `ACPI_ACCESS_*_WIDTH` defines do not provide a way to
test that size is small enough to not cause an overflow when
applied to a 32-bit integer.
Rather than adding more magic numbers, add `ACPI_ACCESS_*_SHIFT`,
`ACPI_ACCESS_*_MAX`, and `ACPI_ACCESS_*_DEFAULT` #defines and
redefine `ACPI_ACCESS_*_WIDTH` in terms of the new #defines.
This was inititally reported on Linux where a size of 102 in
`ACPI_ACCESS_BIT_WIDTH` caused an overflow error in the SPCR
initialization code.
Signed-off-by: Mark Langsdorf <mlangsdo@redhat.com>
=> actypes.h: Expand the ACPI_ACCESS_ definitions

source/common/dmtbdump1.c
The ACPI_AEST_GENERIC_RESOURCE macro is already defined in actbl2.h,
and since it is a Resource type that also exists as an AEST
specification, it is not necessary to output error messages.
Signed-off-by: Shuuichirou Ishii <ishii.shuuichir@fujitsu.com>
=> dmtbdump: Delete the Generic Resource Type error message

source/include/actypes.h, source/include/platform/aclinux.h
This is based on the Linux kernel patch at
https://patchwork.kernel.org/project/linux-acpi/patch/2614912.mvXUDI8C0e@kreacher/
To avoid "performing pointer subtraction with a null pointer has
undefined behavior" compiler warnings, use uintptr_t and offsetof()
that are always available during Linux kernel builds to define
ACPI_UINTPTR_T and the ACPI_TO_INTEGER() and ACPI_OFFSET() macros.
=> Headers: Use uintptr_t and offsetof() in Linux kernel builds

source/components/namespace/nswalk.c
Prevent AcpiNsWalkNamespace () from crashing when called with
StartNode equal to ACPI_ROOT_OBJECT if the Namespace has not
been instantiated yet and AcpiGbl_RootNode is NULL.
=> Namespace: Avoid walking the Namespace if it is not there

source/components/executer/exfldio.c, source/components/hardware/hwregs.c
Remove the second 'know' and 'than'.
Signed-off-by: Tom Rix <trix@redhat.com>
=> cleanup double word in comment

source/common/dmtbdump2.c
Variable named Capabilities was declared twice in one function that caused
variable shadowing. Renaming one of them will fix this issue.
=> iASL: NHLT: Fix variable shadowing

source/components/disassembler/dmwalk.c
AcpiDmPredefinedDescription only works if acpi_parse_object is Named
rather than Common.
Without this check, an ASAN build of the disassembler will fail
with an out of bounds error when trying to disassemble code like
Store(ResourceTemplate() {
QWordMemory (
ResourceProducer, PosDecode, MinFixed, MaxFixed, Cacheable,
ReadWrite, 0, 0, 6, 0, 7, , , , AddressRangeMemory, TypeStatic)
}, Local2)
This particular case was reduced from code in seabios
=> Fix buffer overflow when disassembling anonymous ResourceTemplate()

source/include/actbl2.h
Replace zero-length array with flexible-array member in the struct acpi_table_rgrt definition.
=> Headers: Replace zero-length array with flexible-array member

source/include/platform/acfreebsd.h
- cda7b36af505c7e65b0dbbf7c3d340a6101ca103 broke build on FreeBSD because ``_exit(2)`` requires ``unistd.h``.  It seems Linux was okay because ``source/include/platform/aclinux.h`` included it.  Note other platforms will require similar change.
- Define ``ACPI_TO_INTEGER()`` and ``ACPI_OFFSET()`` macros.  This change should fix #407.
=> Update FreeBSD-specific header

source/compiler/asloptions.c, source/tools/acpixtract/acpixtract.c
Two instances where UINT32 variables should be INT32 types to match them with the values returned from function calls and values being checked for termination states.
=> Fix unsigned/signed int32 variable assignments and comparisons

source/components/tables/tbxfroot.c
When testing a custom hypervisor, we noticed that if there is uninitialized memory at word `0x40e`, the retrieved pointer to **EBDA** can point beyond the boundaries of 640KiB of low memory, possibly to a VGA range. These patches are adding
sanity check for this pointer so that this does not happen.
Further the spec says that only the first KiB of **EBDA** memory is scanned, but it is not guaranteed that **EBDA** will be at least 1KiB in size. For these cases I add code that scans only the memory from **EBDA** start (the pointer) to the end of the low memory.
=> Check EBDA pointer from memory

source/components/executer/exsystem.c
This is analogous to Linux commit c244dc1bc92e Revert "ACPICA: executer/exsystem: Warn about sleeps greater than 10 ms".
=> Revert "executer/exsystem: Warn about sleeps greater than 10 ms"

source/include/actbl1.h
The CXL XOR Interleave Math Structure (CXIMS) is added to the
CXL Early Discovery Table (CEDT). This new structure is defined
in an ECN to the CXL 2.0 specification.
https://www.computeexpresslink.org/spec-landing
Signed-off-by: Alison Schofield <alison.schofield@intel.com>
=> Add the CXIMS structure definition to the CEDT table

source/components/events/evregion.c, source/components/executer/exfield.c, source/components/executer/exserial.c, source/include/acconfig.h, source/include/actypes.h
FFH(Fixed Function Hardware) Opregion is approved to be added in ACPIC 6.5 via
code first approach[1]. It requires special context data similar to GPIO and
Generic Serial Bus as it needs to know platform specific offset and length.
Add support for the special context data needed by FFH Opregion.
FFH OpRegion enables advanced use of FFH on some architectures. For example,
it could be used to easily proxy AML code to architecture-specific behavior
(to ensure it is OS initiated)
Actual behavior of FFH is ofcourse architecture specific and depends on
the FFH bindings. The offset and length could have arch specific meaning
or usage.
[1] https://bugzilla.tianocore.org/show_bug.cgi?id=3598
Signed-off-by: Sudeep Holla <sudeep.holla@arm.com>
=> Add support for FFH Opregion special context data

source/include/actbl1.h
The CXL 3.0 Specification[1] adds two new structures to the CXL Early Discovery Table (CEDT). The CEDT may include zero or more entries of these types:
CXIMS: CXL XOR Interleave Math Structure
Enables the host to find a targets position in an
Interleave Target List when XOR Math is used.
RDPAS: RCEC Downstream Post Association Structure
Enables the host to locate the Downstream Port(s)
that report errors to a given Root Complex Event
Collector (RCEC).
[1]https://www.computeexpresslink.org/spec-landing
Signed-off-by: Alison Schofield <alison.schofield@intel.com>
=> Add CXL 3.0 structures (CXIMS & RDPAS) to the CEDT table

generate/efi/Makefile.config, generate/unix/Makefile.config, generate/unix/iasl/Makefile
For distro maintainers having `-Werror` can delay update of GCC. Since every GCC release might add new warnings that were not yet captured, it might break the build of packages.
With this, distros can now build with `NOWERROR=TRUE` instead of patching either the errors or the makefiles.
The default behavior keeps on using `-Werror`.
Fixes #798
=> Allow disabling of -Werror

source/compiler/dttable1.c
The value stored to 'ParentTable' is never used.
Signed-off-by: Elyes Haouas <ehaouas@noos.fr>
=> compiler/dttable1.c: Fix dead assignment

source/common/dmtbinfo2.c, source/include/actbl2.h
The latest IORT update makes one small addition to SMMUv3 nodes to describe MSI support independently of wired GSIV support.
Signed-off-by: Robin Murphy <robin.murphy@arm.com>
=> IORT: Update for revision E.e

source/include/platform/aclinux.h
Add 64 bit LoongArch architecture by defining ACPI_MACHINE_WIDTH to 64. Useful for acpica tools and incorporating ACPICA into the Firmware Test Suite.
Signed-off-by: Huacai Chen <chenhuacai@loongson.cn>
=> Add support for 64 bit LoongArch compilation.

source/include/acrestyp.h, source/include/actbl2.h, source/include/platform/acenv.h
This continues earlier C99 work to modernize the code to work correctly with compile-time and run-time bounds checkers.
=> Replace fake flexible arrays with actual flexible array members

source/components/namespace/nsrepair.c
Previously AcpiNsSimpleRepair() would crash if ExpectedBtypes contained any combination of ACPI_RTYPE_NONE with a different type, e.g | ACPI_RTYPE_INTEGER because of slightly incorrect logic in the !ReturnObject branch, which wouldn't return AE_AML_NO_RETURN_VALUE for such cases.
Found by Linux Verification Center (linuxtesting.org) with the SVACE static analysis tool.
Signed-off-by: Daniil Tatianin <d-tatianin@yandex-team.ru>
=> nsrepair: handle cases without a return value correctly

source/components/dispatcher/dsmethod.c
A use-after-free in AcpiPsParseAml() after a failing invocaion of AcpiDsCallControlMethod() is reported by KASAN [1] and code inspection reveals that next_walk_state pushed to the thread by AcpiDsCallControlMethod() is freed on errors, but it is not popped from the thread beforehand.  Thus AcpiDsGetCurrentWalkState() called by AcpiPsParseAml() subsequently returns it as the new walk state which is incorrect.
To address this, make AcpiDsCallControlMethod() call AcpiDsPopWalkState() to pop next_walk_state from the thread before returning an error.
This is based on the Linux patch at:
https://patchwork.kernel.org/project/linux-acpi/patch/2669303.mvXUDI8C0e@kreacher/
=> dispatcher: Fix error code path in AcpiDsCallControlMethod()

source/components/namespace/nsrepair2.c
The following commit add function tracing macros for the namespace repiar mechanism.
commit 87b8dba05b4cf8c111948327023c710e2b6b5a05
Add function trace macros to improve namespace debugging
But it missed the trace macro for the entry of NsRepair_HID(). Let's add it.
Signed-off-by: Xiongfeng Wang <wangxiongfeng2@huawei.com>
=> Add missing macro ACPI_FUNCTION_TRACE() for AcpiNsRepair_HID()

source/components/hardware/hwvalid.c
Microsoft introduced support in Windows XP for blocking port I/O to various regions.  For Windows compatibility ACPICA has adopted the same protections and will disallow writes to those (presumably) the same regions.
On some systems the AML included with the firmware will issue 4 byte long writes to 0x80.  These writes aren't making it over because of this blockage. The first 4 byte write attempt is rejected, and then subsequently 1 byte at a time each offset is tried. The first at 0x80 works, but then the next 3 bytes are rejected.
This manifests in bizarre failures for devices that expected the AML to write all 4 bytes.  Trying the same AML on Windows 10 or 11 doesn't hit this failure and all 4 bytes are written.
Either some of these regions were wrong or some point after Windows XP …
=> ACPICA: hwvalid: Drop port I/O validation

source/common/dmtbinfo2.c, source/include/actbl2.h
Signed-off-by: Xiongfeng Wang <wangxiongfeng2@huawei.com>
=> ACPI 6.5: MADT: add support for trace buffer extension in GICC

source/components/events/evxfregn.c, source/include/acpixf.h
ACPI-2.0 says that the EC OpRegion handler must be available immediately
(like the standard default OpRegion handlers):
Quoting from the ACPI spec version 6.3: "6.5.4 _REG (Region) ...
2. OSPM must make Embedded Controller operation regions, accessed via
the Embedded Controllers described in ECDT, available before executing
any control method. These operation regions may become inaccessible
after OSPM runs _REG(EmbeddedControl, 0)."
So the OS must probe the ECDT described EC and install the OpRegion handler
before calling AcpiEnableSubsystem() and AcpiInitializeObjects().
This is a problem because calling AcpiInstallAddressSpaceHandler()
does not just install the OpRegion handler, it also runs the EC's _REG
method. This _REG method may rely on initialization done by the _INI
methods of …
=> Make AddressSpaceHandler Install and _REG execution 2 separate steps

source/components/namespace/nsxfname.c, source/include/acpixf.h
Hello,
This pull request contains a single patch, constifying the pathname argument to AcpiGetHandle. The objective is to allow passing a const pathname to the function, in order to avoid having to make a copy of it. This isn't needed by acpica per se, but by another caller in Linux.
It's the first time I'm using Github to do this, let's see how this works...
- Sakari
=> Constify AcpiGetHandle pathname argument

source/components/dispatcher/dswexec.c
In our tests we get UBSAN warning coming from ACPI parser. This is
caused by trying to resolve operands when there is none.
Signed-off-by: Amadeusz Sławiński <amadeuszx.slawinski@linux.intel.com>
Reviewed-by: Cezary Rojewski <cezary.rojewski@intel.com>
=> ACPICA: Fix operand resolution

source/components/namespace/nsrepair2.c
This is an upstream ACPICA version of Linux commit 6511a8b5b7a6 ("Revert "ACPICA: Fix memory leak caused by _CID repair function"") that reverted a problematic change in the ACPICA code.
Please consider for merging.
=> Revert "Fix memory leak caused by _CID repair function"

source/include/acrestyp.h, source/include/actbl2.h, source/include/platform/acenv.h
Reverts acpica/acpica#813
Causes many build errors on MS Visual C:
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2016	C requires that a struct or union has at least one member (compiling source file ..\..\source\COMPONENTS\Disassembler\dmwalk.c)	AcpiExec	c:\acpica\source\include\acrestyp.h	932
=> Revert "Replace fake flexible arrays with actual flexible array members"

source/include/actbl2.h
Like many tables, this is a header followed by multiple subtables of
varying self-identifying types, and ACPICA does not normally add a field
for the subtables, instead relying on pointer arithmetic past the end of
the first header struct, since indexing a flexible array member is
meaningless for variable-length entries. If we really wanted a field for
this, we could use a UINT8 flexible array member, but it contradicts the
current style. Using void *, however, is categorically wrong, as ACPI
tables never contain native C-language pointers.
=> Headers: Delete bogus NodeArray array of pointers from AEST table

source/common/adisasm.c
Most invocations of `AcpiPsDeleteParseTree (AcpiGbl_ParseOpRoot);` are followed by `AcpiGbl_ParseOpRoot = NULL;`, but there was one which was missing this. Fixes #841.
=> iasl: Set AcpiGbl_ParseOpRoot to NULL when freed

source/components/debugger/dbnames.c
ACPI_ALLOCATE_ZEROED may fails, ObjectInfo might be null and will cause null pointer dereference later.
=> check null return of ACPI_ALLOCATE_ZEROED in AcpiDbDisplayObjects

source/common/dmtbdump2.c, source/compiler/asltypes.h, source/include/acrestyp.h, source/include/actbl1.h, source/include/actbl2.h, source/include/actypes.h, source/include/amlresrc.h, source/include/platform/acefiex.h, source/include/platform/acgcc.h
Hello!
This is a more comprehensive series to address all the technical debt related to 1-element and 0-length arrays in ACPICA code, with the goal of making this behave correctly in the Linux kernel when built with GCC and Clang's new `-fstrict-flex-arrays=3` option.
I did per-patch A/B build output analysis checking for `.text` and `.data` section changes, solving or noting any differences in each patch. Specifically, this series seems to have found possibly 2 bugs in existing size calculations, noted in their individual patches:
- `AcpiDmDumpNfit()`'s calculation of `ACPI_NFIT_INTERLEAVE` appears to have been originally wrong, but is now fixed.
- `AcpiDmDumpDmar()`'s calculation of `ACPI_DMAR_ANDD` seems suspicious, but the existing result appears to be used as a table offset. It's …
=> Flex array transformations, take 2

source/components/resources/rsmisc.c
Before this change we see the following UBSAN stack trace in Fuchsia:
```
#0    0x000020c1f68c9959 in AcpiRsConvertAmlToResource(ACPI_RESOURCE*, AML_RESOURCE*, ACPI_RSCONVERT_INFO*) ../../third_party/acpica/source/components/resources/rsmisc.c:244 <platform-bus-x86.so>+0x2d0959
#1.2  0x000020e5d259f77f in ubsan_GetStackTrace() compiler-rt/lib/ubsan/ubsan_diag.cpp:41 <libclang_rt.asan.so>+0x3d77f
#1.1  0x000020e5d259f77f in MaybePrintStackTrace() compiler-rt/lib/ubsan/ubsan_diag.cpp:51 <libclang_rt.asan.so>+0x3d77f
#1    0x000020e5d259f77f in ~ScopedReport() compiler-rt/lib/ubsan/ubsan_diag.cpp:387 <libclang_rt.asan.so>+0x3d77f
#2    0x000020e5d25a0385 in handleTypeMismatchImpl() compiler-rt/lib/ubsan/ubsan_handlers.cpp:137 <libclang_rt.asan.so>+0x3e385
#3    0x000020e5d259fead in …
```
=> Avoid undefined behavior: load of misaligned address

source/components/resources/rslist.c
Before this change we see the following UBSAN stack trace in Fuchsia:
```
#0    0x000020d00518f81a in AcpiRsConvertAmlToResources(UINT8*, UINT32, UINT32, UINT8, void**) ../../third_party/acpica/source/components/resources/rslist.c:104 <platform-bus-x86.so>+0x2cd81a
#1.2  0x00002348b567277f in ubsan_GetStackTrace() compiler-rt/lib/ubsan/ubsan_diag.cpp:41 <libclang_rt.asan.so>+0x3d77f
#1.1  0x00002348b567277f in MaybePrintStackTrace() compiler-rt/lib/ubsan/ubsan_diag.cpp:51 <libclang_rt.asan.so>+0x3d77f
#1    0x00002348b567277f in ~ScopedReport() compiler-rt/lib/ubsan/ubsan_diag.cpp:387 <libclang_rt.asan.so>+0x3d77f
#2    0x00002348b5673385 in handleTypeMismatchImpl() compiler-rt/lib/ubsan/ubsan_handlers.cpp:137 <libclang_rt.asan.so>+0x3e385
#3    0x00002348b5672ead in …
```
=> Avoid undefined behavior: member access within misaligned address

source/include/platform/aclinux.h
84449c1eef1c0d092b037dc4c2c60cec5d5cc6c4 fixed this for Linux kernel builds, but not Linux userspace builds.
Before this change we see the following UBSAN stack trace in Fuchsia:
```
../../third_party/acpica/source/components/tables/tbfadt.c:536:39: runtime error: member access within null pointer of type 'ACPI_TABLE_FADT' (aka 'struct acpi_table_fadt')
#0 0x564860b5ee9b in AcpiTbConvertFadt ../../third_party/acpica/source/components/tables/tbfadt.c:536:39
#1 0x564860b5edb4 in AcpiTbCreateLocalFadt ../../third_party/acpica/source/components/tables/tbfadt.c:461:5
#2 0x564860b5e5c6 in AcpiTbParseFadt ../../third_party/acpica/source/components/tables/tbfadt.c:371:5
#3 0x564860b5c485 in AcpiTbParseRootTable ../../third_party/acpica/source/components/tables/tbutils.c:407:13
#4 0x564860b6401a …
```
=> Avoid undefined behavior: member access within null pointer

source/components/dispatcher/dswstate.c
Before this change we see the following UBSAN stack trace in Fuchsia:
```
#0    0x000021e4213b3302 in AcpiDsInitAmlWalk(ACPI_WALK_STATE*, ACPI_PARSE_OBJECT*, ACPI_NAMESPACE_NODE*, UINT8*, UINT32, ACPI_EVALUATE_INFO*, UINT8) ../../third_party/acpica/source/components/dispatcher/dswstate.c:682 <platform-bus-x86.so>+0x233302
#1.2  0x000020d0f660777f in ubsan_GetStackTrace() compiler-rt/lib/ubsan/ubsan_diag.cpp:41 <libclang_rt.asan.so>+0x3d77f
#1.1  0x000020d0f660777f in MaybePrintStackTrace() compiler-rt/lib/ubsan/ubsan_diag.cpp:51 <libclang_rt.asan.so>+0x3d77f
#1    0x000020d0f660777f in ~ScopedReport() compiler-rt/lib/ubsan/ubsan_diag.cpp:387 <libclang_rt.asan.so>+0x3d77f
#2    0x000020d0f660b96d in handlePointerOverflowImpl() compiler-rt/lib/ubsan/ubsan_handlers.cpp:809 …
```
=> Avoid undefined behavior: applying zero offset to null pointer

source/include/platform/acenv.h, source/include/platform/aczephyr.h, source/os_specific/service_layers/oszephyr.c
The acpica will be integrated as module into Zephyr project for enable acpi bus driver. This patch is for enable os specific support layer for Zephyr.
=> add os specific support for Zephyr RTOS

source/components/resources/rsaddr.c
This changed in f98909b7928cac8c5328e4852ad5a7ea671204fb, seemingly by accident.
=> Move ACPI_FUNCTION_ENTRY to function entry

source/components/utilities/utdebug.c, source/include/platform/aclinux.h
We're storing a persistent pointer to an ephemeral local variable which technically is a dangling pointer and the compiler is correct. However, since we never indirect the pointer, this is a safe operation and we can suppress the warning.
Also, some C run-times (like MUSL) aren't including <stdint.h> indirectly so we must include it explicitly or we won't have the type definition for uintptr_t.
Fixes issue #867.
=> Fix GCC 12 dangling-pointer warning

source/include/platform/aczephyr.h
fix for conflict SEEK_SET/SEEK_END duplicate macro while run CI job.
=> fix for conflict macro definition on zephyr interface

source/common/dmtbdump2.c
In AcpiDmDumpMadt(), compute and check the Offset before attempting to dereference Subtable fields to prevent a read overflow.
I found this issue while debugging #841. Effectively, some debug statements were trying to dereference data from the updated Subtable pointer before checking if the Offset made it past the end of the table. This PR just moves some lines around to compute and check Offset before trying to access data for debug printing.
=> iasl: check Offset before Subtable dereference

source/components/executer/exserial.c
Make the code simpler and more readable.
=> exserial.c: replace ternary operator with ACPI_MIN()

source/include/aclocal.h
Avoid trailing semicolons in macro, and it's not readable to put macro ACPI_STATE_COMMON and other variables in the same line.
So modify the macro and just put it in a single line.
=> ACPICA: Modify ACPI_STATE_COMMON

source/components/debugger/dbcmds.c, source/components/debugger/dbinput.c, source/include/acdebug.h, source/include/acglobal.h, source/include/aclocal.h, source/include/acnames.h, source/tools/acpiexec/aeinstall.c
Acpiexec lacked support for GED devices (relevant for HW-reduced platforms), where an interrupt (of a given GSIV) triggers the execution of the _EVT method of that GED.
This patch set introduces support for interrupt simulation in acpiexec.
=> Add support for Interrupt in acpiexec

source/include/actbl1.h
A spelling correction for CDAT definition and the other adding additional CDAT defines.
=> CDAT updates

source/components/dispatcher/dswstate.c
'object' is known to be NULL at this point. There is little value to log it twice in the error message.
=> Slightly simplify an error message in AcpiDsResultPush()

source/include/actbl3.h
Replace magic number with a define. Linux kernel code will utilize this define.
=> Add a define for size of acpi_srat_generic_affinity DeviceHandle

source/components/parser/psopcode.c
According to the ACPI specification 19.6.134, no argument is required to be passed for ASL Timer instruction. For taking care of no argument, AML_NO_OPERAND_RESOLVE flag is added to ASL Timer instruction opcode.
When ASL timer instruction interpreted by ACPI interpreter, getting error. After adding AML_NO_OPERAND_RESOLVE flag to ASL Timer instruction opcode, issue is not observed.
============================================================= UBSAN: array-index-out-of-bounds in acpica/dswexec.c:401:12 index -1 is out of range for type 'acpi_operand_object *[9]' CPU: 37 PID: 1678 Comm: cat Not tainted
6.0.0-dev-th500-6.0.y-1+bcf8c46459e407-generic-64k HW name: NVIDIA BIOS v1.1.1-d7acbfc-dirty 12/19/2022 Call trace:
dump_backtrace+0xe0/0x130
show_stack+0x20/0x60
dump_stack_lvl+0x68/0x84 …
=> Add AML_NO_OPERAND_RESOLVE flag to Timer

source/common/dmtbinfo2.c
There is a minor issue with iASL compile and dump capability for RISC-V PLIC interrupt controller structure.
Flags field in RISC-V PLIC APIC structure gets printed twice by iASL. Remove the redundant one.
=> RISC-V: Remove redundant Flags print

source/include/actbl2.h
Device configuration structures are plenty so declare a struct for each known variant. While these kind of duplicate few types present in actbl2.h already, change is motivated by usage improvements - simplicity and shorten wording. Intention is to have them replacing the existing members in the future.
=> NHLT: Declare device configuration types

source/include/platform/aczephyr.h, source/os_specific/service_layers/oszephyr.c
add support for uefi as well as non uefi platform for zephyr rtos.
Also add support for 32bit platforms.
=> os_specific: zephyr: add generic platform support

source/include/actbl1.h
Add EINJ CXL error types added in ACPI v6.5 (Section 18.6.4, Table 18.30).
=> actbl1.h: Add EINJ CXL error types

source/common/dmtbdump.c, tests/aslts/doc/docs/TestOfOperands, tests/aslts/src/runtime/collections/functional/module/object.asl
There is an if statement where both paths print the same output, hence the if is redundant and can be replace with just the print.
=> dmtbdump: remove duplicated code for both paths of an if statement

source/common/dmtbdump2.c
The failure check on Status is redundant as it is being checked in the previous if statement and before the if statement too. It is impossible for ACPI_FAILURE(Status) to be true because the previous checks have already returned out of the function at this point. Remove it.
=> dmtbdump2: remove redundant failure check on Status

source/os_specific/service_layers/oszephyr.c
update AcpiOsGetTimer implementation with arch/platform specific implementation (acpi_timer_get) instead of using sys_clock_cycle_get_64 which might internally use hpet timer etc. if it enabled as system timer and can cause raise condition if AcpiOsGetTimer invoked before those timer driver instantiate.
=> os_specific: zephyr: update AcpiOsGetTimer with arch or platform specific implementation

source/include/platform/acgcc.h
Fix access to array members wrapped into ACPI_FLEX_ARRAY when compiled in C++ (with gcc).
In C++, an empty struct has a size of 1, shifting the actual member by one byte. As this is a C99 workaround, disable it when compiling under C++.
As a reference: https://github.com/torvalds/linux/blob/master/include/uapi/linux/stddef.h#L32
=> acgcc: Fix C++ issue with ACPI_FLEX_ARRAY

source/include/aclocal.h, source/os_specific/service_layers/oszephyr.c, tests/aslts/adm/BugState/ALLBUGS, tests/aslts/adm/BugState/ALLBUGS_DUP, tests/aslts/src/runtime/collections/bdemo/ACPICA/0063/File1.asl, tests/aslts/src/runtime/collections/functional/reference/SPEC
There are a handful of spelling mistakes in various files as found using codespell. Fix these. No code changes.
=> Fix various spelling mistakes in text files and code comments

source/include/actbl1.h
Fix CXL 3.0 structure (RDPAS) in the CEDT table
struct acpi_cedt_rdpas does not match with CXL r3.0 9.17.1.5 Table 9-24. 
reserved1 and length fields are already added by struct acpi_cedt_header.
=> Fix CXL 3.0 structure (RDPAS) field in the CEDT table

source/compiler/aslfiles.c
If a code table which contains errors is passed to iasl followed by a data table, AePrintErrorSourceLine will call FlGetFileHandle with an InFileId of ASL_FILE_SOURCE_OUTPUT and a non-NULL Filename.
When FlGetFileHandle searches AslGbl_FilesList, it first encounters the entry for the data table, which has no Files entry for this InFileId.
It then passes a NULL value to strcmp which can cause a segfault.
The bug was introduced in https://github.com/acpica/acpica/commit/997f6ca123771073a6f62738734a561d2dd056ac when FlGetFileHandle was added. Before, AePrintErrorSourceLine checked if AslGbl_Files[ASL_FILE_SOURCE_OUTPUT].Handle was NULL before proceeding.
Simple repro:
```
❯ ./iasl -T dsdt
Created ACPI table template for [DSDT], written to "dsdt.asl"
❯ ./iasl -T facp
Created ACPI table …
```
=> Fix segfault when error-checking mixed table types

source/components/events/evxfgpe.c
Because of a typo we would inverse the mask twice, thus producing a bogus result.
=> events/evxfgpe: correctly clear GPE_AUTO_ENABLED in AcpiSetupGpeForWake

source/common/dmtables.c, source/compiler/aslcompile.c, source/compiler/aslglobal.h, source/compiler/aslhelp.c, source/compiler/asloptions.c
The output from iasl -d included a timestamp. This meant that each execution returned different output. To provide a means of making the output deterministic, use the value of the SOURCE_DATE_EPOCH environment variable in preference to the current time.
See https://reproducible-builds.org/specs/source-date-epoch/ for background on the environment variable.
=> Add option to make output deterministic

source/components/events/evgpeinit.c
This was used to log the number of newly discovered GPEs post table load in AcpiEvUpdateGpes, but we never incremented the number inside AcpiEvMatchGpeMethod so that was never logged.
=> events/evgpeinit: don't forget to increment registered GPE count

source/components/debugger/dbnames.c
Errors in AcpiEvaluateObject can lead to incorrect state of Buffer. This can lead to access to data in previously ACPI_FREEd Buffer and secondary ACPI_FREE to the same Buffer later.
Handle errors in AcpiEvaluateObject the same way it is done earlier with AcpiNsHandleToPathname.
=> ACPICA: debugger: check status of AcpiEvaluateObject in AcpiDbWalkForFields

source/components/utilities/utdelete.c, source/components/utilities/utinit.c, source/include/platform/acenv.h, source/include/platform/achaiku.h
These fixes were done in Haiku's copy of the ACPICA sourcecode, but not sent to ACPICA yet.
It would ease our maintenance process if they could be upstreamed. Thanks!
The first two commits are changes only in Haiku specific code, and should cause no problems.
The third one was already discussed for upstreaming, but was never merged. Let me know if I implemented correctly what was described.
=> Upstream changes in Haiku support

source/compiler/aslcompiler.h, source/compiler/aslcompiler.l, source/compiler/aslmap.c, source/compiler/aslparser.y, source/compiler/aslresource.c, source/compiler/aslresources.y, source/compiler/aslrestype2d.c, source/compiler/asltokens.y, source/compiler/asltypes.y, source/include/aclocal.h
The DWordPcc (alongside WordPcc and QWordPcc) were accepted to ACPI inclusion via a code-first process.
This patch implements support in iASL for DWordPcc.
ASWG ticket: https://mantis.uefi.org/mantis/view.php?id=2429
Bugzilla ticket: https://bugzilla.tianocore.org/show_bug.cgi?id=4594
Change-Id: I06d61644b428bed2802a76abff59ceb1c79930da
=> Implement the DWordPCC Resource Descriptor Macro

source/components/resources/rsaddr.c
explicitly allow QWord address space description type to be 0xA to indicate it refers to a Platform
Communication channel
IAW  ACPI_ECR_PCC_DESCRIPTORS_CF_V2
https://bugzilla.tianocore.org/show_bug.cgi?id=4594
An entity in a DSDT or in SSDTs that requires
a platform communication channel table (PCCT) entry to communicate with a remote service will have a single value that is the index of the entry in the PCCT.
This data type with have a ResourceType value of 0xA.
This value indicates that the type shares the same footprint as a DWordSpace section.
=> Allow PCC Data Type in MCTP resource.

source/components/tables/tbfadt.c, source/components/tables/tbutils.c
The FACS is optional even on hardware reduced platforms, and may exist for the purpose of communicating the hardware_signature field to provke a clean reboot instead of a resume from hibernation.
=> Detect FACS even for reduced hardware platforms

source/components/executer/exsystem.c, source/include/acoutput.h
Implement ACPI_WARNING_ONCE and ACPI_ERROR_ONCE and use them to stop nagging the user about every Stall() call that violates the spec
=> Implement ACPI_WARNING_ONCE and ACPI_ERROR_ONCE

source/components/parser/psargs.c
If AcpiPsGetNextNamepath() fails, the previously allocated ACPI_PARSE_OBJECT needs to be freed before returning the status code.
The issue was first being reported on the Linux ACPI mailing list:
https://lore.kernel.org/linux-acpi/56f94776-484f-48c0-8855-dba8e6a7793b@yandex.ru/T/
=> Fix memory leak if AcpiPsGetNextNamepath() fails

source/components/disassembler/dmwalk.c
Previous fix at 09a9a0808ba4997173ecb5c6ec3bdb1f2d0d50b5 was intended to capture the AcpiDmPredefinedDescription call in the conditional but the original call was left in place. This code still results in ASAN reporting a heap overflow on the minimal test case unless the original call is removed.
Test ASL derived from commit example:
```asl
DefinitionBlock ("", "DSDT", 2, "Intel", "_DSDT_01", 0x00000001)
{
Method (TEST)
{
Local0 = ResourceTemplate ()
{
QWordMemory (ResourceProducer, PosDecode, MinFixed, MaxFixed, Cacheable, ReadWrite,
0, // Granularity
0, // Range Minimum
6, // Range Maximum
0, // Translation Offset
7, // Length
,, , AddressRangeMemory, TypeStatic)
}
Return (Local0)
}
}
```
Failing run at latest upstream commit:
```
❯ ASAN_OPTIONS=detect_leaks=0 ./iasl dsdt.asl
Intel ACPI …
```
=> Anonymous ResourceTemplate dissassembly fix

source/components/debugger/dbconvert.c
ACPI_ALLOCATE_ZEROED may fails, Elements might be null and will cause null pointer dereference later.
=> check null return of ACPI_ALLOCATE_ZEROED in AcpiDbConvertToPackage

source/components/parser/psargs.c
If AcpiPsGetNextField() fails, the previously created field list needs to be properly disposed before returning the status code.
=> Fix memory leak if AcpiPsGetNextField() fails

source/common/dmtbdump.c
AcpiDmValidateFadtLength was missing an expected length check for FADT revision 6
AcpiDmDumpFadt was calling the AcpiDmDumpTable with AcpiDmTableInfoFadt6 for table lengths greater than ACPI_FADT_V3_SIZE instead of lengths greater than ACPI_FADT_V5_SIZE
This resulted in a warning in the disassembly of a revision 5 FADT:
```
/**** ACPI table terminates in the middle of a data structure! (dump table)
CurrentOffset: 10C, TableLength: 10C ***/
```
To replicate, I created an FADT with iasl: `iasl -T facp` and edited the resulting ASL to be revision 5, changed length to 10C to match and removed the rev-6-only field `HypervisorId`. It looks like this:
```
[000h 0000 004h]                   Signature : "FACP"    [Fixed ACPI Description Table (FADT)]
[004h 0004 004h]                Table Length : …
```
=> Fix FADT size checks in data table disassembler

source/components/executer/exconvrt.c
This series changes the handling of integers in ToHexString(), see Issue #827 for details.
The following ASL code was used to test the behavior of ToHexString() with integer arguments under both Windows and ACPICA: [ssdt.txt](https://github.com/acpica/acpica/files/13194389/ssdt.txt).
The output of \_SB.TE08, \_SB.TE16, \_SB.TE32 and \_SB.TE64 was verified to be the same under Windows and ACPICA
except when encountering 64 bit constants in 32 bit tables. In such a case, Windows would not truncate the output of \_SB.TE64,
but ACPICA did.
Since using 64 bit integers in a 32 bit table is unsupported anyway and the chance of encountering this in the wild are
rather low, i decided to ignore this special case.
As a side note, something similar was already done in commit f9efaa885dc3 …
=> Modify Integer handling in ToHexString()

source/components/executer/exregion.c
Revert changes made in commit 381f8561ee4e ("Do not cross page boundaries when mapping operation regions."). The original intention of that commit was to prevent memory mappings for operation regions from crossing page boundaries, as it can cause warnings in case of different page attributes.
However, it was discovered that when this condition occurs, mapping is done until the end of the boundary, but still attempts to read/write the entire length of the map, resulting in a NULL pointer deference. For instance, if there is a request to map four bytes but only one byte is mapped because it reaches the end of the current page boundary, there is still an attempt to read/write four bytes, causing a NULL pointer dereference.
Instead, map the complete length, as there is no restriction in the …
=> acpica: Revert "Do not cross page boundaries when mapping operation regions."

source/components/resources/rsdump.c
Only include the functions AcpiRsDumpResourceList and AcpiRsDumpIrqList if ACPI_DEBUGGER is defined, as specified in the header. This avoid the compiler warning by adding the ifdef for ACPI_DEBUGGER.
The header: https://github.com/acpica/acpica/blob/master/source/include/acresrc.h#L470
=> Avoid warning for Dump Functions

source/common/dmtbinfo1.c, source/include/actbl1.h
Redefine the 2 reserved bytes at offset 28 of Memory Side Cache Information Structure as "Address Mode" and add defines of the new value.
* 0 - Reserved (Unkown Address Mode)
* 1 - Extended-linear (N direct-map aliases linearly mapped)
* 2..65535 - Reserved (Unknown Address Mode)
Reference: Mantis ID: 2459
=> HMAT: Add extended linear address mode to MSCIS

source/common/dmtbinfo2.c, source/include/actbl2.h
The IORT spec, Issue E.f (April 2024), adds a new CANWBS bit to the Memory Access Flag field in the Memory Access Properties table, mainly for a PCI Root Complex.
This CANWBS defines the coherency of memory accesses to be not marked IOWB cacheable/shareable. Its value further implies the coherency impact from a pair of mismatched memory attributes (e.g. in a nested translation case):
0x0: Use of mismatched memory attributes for accesses made by this
device may lead to a loss of coherency.
0x1: Coherency of accesses made by this device to locations in
Conventional memory are ensured as follows, even if the memory
attributes for the accesses presented by the device or provided by
the SMMU are different from Inner and Outer Write-back cacheable,
Shareable.
=> IORT: Update for revision E.f

generate/unix/Makefile.config
Then DEBUG is set to TRUE, the resulting binaries contain debugging information. Since those binaries are however always stripped during installation, this debug information is effectively unusable.
Fix this by not stripping the resulting binaries during installation in such a case.
Fixes: a7a2de9b80be ("Makefile: add debug flag")
=> Do not strip debug info when debugging is enabled

source/components/executer/exprep.c
Solves https://github.com/acpica/acpica/issues/963
Not sure whether this is most clean/correct way to exit. Attempt to return error status or delete object description results in further failures. With just `break` decompiling finally completes:
```
Intel ACPI Component Architecture
ASL+ Optimizing Compiler/Disassembler version 20240322
Copyright (c) 2000 - 2023 Intel Corporation
File appears to be binary: found 61249 non-ASCII characters, disassembling
Binary file appears to be a valid ACPI table, disassembling
Input file /mnt/c/Users/alexv/Desktop/iasl-win-20240321/DSDT.aml, Length 0x3E413 (254995) bytes
ACPI: DSDT 0x0000000000000000 03E413 (v02 QCOMM  SDM8380  00000003 MSFT 05000000)
Pass 1 parse of [DSDT]
Pass 2 parse of [DSDT]
Parsing Deferred Opcodes …
```
=> iasl: handle empty ConnectionNode

source/common/dmtbdump1.c, source/common/dmtbdump2.c, source/common/dmtbdump3.c
Some fixes that were in my tree that touch on table dumping.  In particular for DBG2, SLIC and PHAT tables, subtable offsets were either not always calculated properly or used problematic arithmetic with unsigned variables.
Test cases for these can sometimes be very simple; for PHAT, for example, all you have to do is run "iasl -T phat" to get a segfault.
=> Fixes 20240322

source/common/dmtable.c, source/compiler/aslparseop.c, source/compiler/prmacros.c
There are a handful of output strings that have a trailing space before a \n character. The spaces seem to be extraneous and can be removed.
=> Remove extraneous spaces before \n character

source/common/dmtbdump2.c
This series contains various fixes for the PHAT table parser:
- fixing a possible segfault when encountering invalid device paths
- fixing displayed offsets
- fix parsing of firmware health records
I tested the changes on a PHAT table from the Acer Predator Triton PT14-51, and everything seems to work.
=> PHAT: Various fixes

source/common/dmtbdump3.c
Currently the offset into the SLIC table is being computing by adding an offset onto the Table pointer but because Table is a ACPI_TABLE_HEADER pointer type the offset is actually in multiples of the size of the ACPI_TABLE_HEADER struct. Fix this by casting Table to a UINT8 * to make the pointer arithmetic work in terms of octects (bytes).
Detected when integrating ACPICA into the Firmware Test Suite and I noticed the SLIC table data was being fetched from a bogus location.
Fixes: 1672c9dc6446 ("Correct dumping of SLIC tables")
=> Fix pointer offset into SLIC table

source/include/actbl1.h
Add shareable and read only flag bit definitions to decode DSMAS flags field.
=> CDAT/DSMAS: Add shareable and read only flag bit definitions

source/include/actbl1.h
Add EINJV2_GET_ERROR_TYPE as defined in the new specs(1)(2).
Approved ACPI spces for EINJv2:
(1) https://bugzilla.tianocore.org/show_bug.cgi?id=4615
(2) https://bugzilla.tianocore.org/attachment.cgi?id=1446
=> Add EINJV2_GET_ERROR_TYPE

source/tools/acpixtract/acpixtract.c
Fix a regression found by @paulmenzel
=> tools/acpixtract: handle AX_OPTIONAL_TABLES correctly

source/components/events/evxfregn.c
This bug was first introduced in c9e011695, where the author of the patch probably meant to do DeleteMutex instead of ReleaseMutex. The mutex leak was noticed later on and fixed in bc43c878, but the bogus MutexRelease line was never removed, so do it now.
Fixes: c9e011695 ("Fix race in GenericSerialBus (I2C) and GPIO OpRegion parameter handling")
=> events/evxfregn: don't release the ContextMutex that was never acquired

source/components/parser/psobject.c
I'm Seunghun Han, and I work for National Security Research Institute of
South Korea.
I have been doing a research on ACPI and found an ACPI cache leak in ACPI
early abort cases.
Boot log of ACPI cache leak is as follows:
[    0.352414] ACPI: Added _OSI(Module Device)
[    0.353182] ACPI: Added _OSI(Processor Device)
[    0.353182] ACPI: Added _OSI(3.0 _SCP Extensions)
[    0.353182] ACPI: Added _OSI(Processor Aggregator Device)
[    0.356028] ACPI: Unable to start the ACPI Interpreter
[    0.356799] ACPI Error: Could not remove SCI handler (20170303/evmisc-281)
[    0.360215] kmem_cache_destroy Acpi-State: Slab cache still has objects
[    0.360648] CPU: 0 PID: 1 Comm: swapper/0 Tainted: G        W
4.12.0-rc4-next-20170608+ #10
[    0.361273] Hardware name: innotek GmbH …
=> acpi: acpica: fix acpi parse and parseext cache leaks

source/components/dispatcher/dsutils.c
I found an ACPI cache leak in ACPI early termination and boot continuing case.
When early termination occurs due to malicious ACPI table, Linux kernel
terminates ACPI function and continues to boot process. While kernel terminates
ACPI function, kmem_cache_destroy() reports Acpi-Operand cache leak.
Boot log of ACPI operand cache leak is as follows:
>[    0.585957] ACPI: Added _OSI(Module Device)
>[    0.587218] ACPI: Added _OSI(Processor Device)
>[    0.588530] ACPI: Added _OSI(3.0 _SCP Extensions)
>[    0.589790] ACPI: Added _OSI(Processor Aggregator Device)
>[    0.591534] ACPI Error: Illegal I/O port address/length above 64K: C806E00000004002/0x2 (20170303/hwvalid-155)
>[    0.594351] ACPI Exception: AE_LIMIT, Unable to initialize fixed events (20170303/evevent-88)
>[    0.597858] …
=> acpi: acpica: fix acpi operand cache leak in dsutils.c

source/compiler/aslcache.c
This was doing arithmetic math with a null pointer on first access which runs afoul of ubsan.
I was able to reproduce this with any input file at all as long as ubsan was enabled, including this simple DSDT:
```
DefinitionBlock ("", "DSDT", 2, "Intel", "_DSDT_01", 0x00000001)
{
Method (DS01)
{
}
}
```
Yielding:
```
acpica/source/compiler/aslcache.c:213:33: runtime error: applying non-zero offset 70 to null pointer
SUMMARY: UndefinedBehaviorSanitizer: nullptr-with-nonzero-offset acpica/source/compiler/aslcache.c:213:33
```
This pattern of null pointer access can be verified on code inspection, and is relieved by simply skipping the arithmetic check if the pointer is null and proceeding to the body of the if-statement where the pointer values are populated, rendering pointer arithmetic …
=> Add null pointer check to UtLocalCacheCalloc

source/components/utilities/utdelete.c
There is a spelling mistake in a literal string. Fix it.
Fixes: a171306ed1a1 ("Reference count: add additional debugging details)
=> Utilities: Fix spelling mistake "Incremement" -> "Increment"

source/common/dmrestag.c, source/components/namespace/nsnames.c, source/components/namespace/nsrepair2.c, source/include/aclocal.h, source/include/actypes.h, source/include/platform/acgcc.h
In order to distinguish character arrays from C Strings (i.e. strings with
a terminating NUL character), add support for the "nonstring" attribute
provided by GCC. (A better name might be "ACPI_NONCSTRING", but that's
the attribute name, so stick to the existing naming convention.)
GCC 15's -Wunterminated-string-initialization will warn about truncation
of the NUL byte for string initializers unless the destination is marked
with "nonstring". Prepare for applying this attribute to the project.
https://gcc.gnu.org/onlinedocs/gcc/Common-Variable-Attributes.html#index-nonstring-variable-attribute
=> Introduce "nonstring" annotations

source/components/executer/exserial.c
The initial commit that introduced support for FFixedHW operation regions did add a special case in the AcpiExReadSerialBus If, but forgot to actually handle it inside the switch, so add the missing case to prevent reads from failing with AE_AML_INVALID_SPACE_ID.
Fixes: fad527b6e76 ("Add support for FFH Opregion special context data")
=> exserial: don't forget to handle FFixedHW opregions for reading

source/compiler/aslmethod.c
In `MtMethodAnalysisWalkBegin`, for the case `PARSEOP_DEVICE`; the comment does not tell from which ACPI specs an object must not contain both `_HID` and `_ADR`.
[A discussion in Xen project]( https://lore.kernel.org/all/20241222161444.1558599-2-Ariel.Otilibili-Anieli@eurecom.fr/) showed the wording has changed:
From  [ACPI 2.0 (Jul. 27, 2000; Section 6.1, page 146)](https://uefi.org/sites/default/files/resources/ACPI_2.pdf):
> A device object must contain either an _HID object or an _ADR object, but can contain both.
To [ACPI 6.0 (April 2015; Section 6.1, page 278)](https://uefi.org/sites/default/files/resources/ACPI_6.0.pdf),
>A device object must contain either an _HID object or an _ADR object, but should not contain both.
And from [ACPI 6.3, Errata A (October 2020; Section 6.1, page …
=> source/compiler: made `PARSEOP_DEVICE` consistent with ACPI 6.3, Errata A

source/components/utilities/utcache.c
In the acpica/utcache.c file, adjust the position of the "ACPI_MEM_TRACKING(cache->total_allocated++);" code line to ensure that the increment operation on total_allocated is included within the ACPI_DBG_TRACK_ALLOCATIONS configuration.
=> Adjust the position of code lines.

source/components/utilities/utprint.c
A single glance at the ‘fix’ introduced in #568 should make it clear that it cannot possibly work when `(String >> 32) != 0`.  First, nothing gets written to the destination because `End < String`.  Then, because `End < Pos`, it tries to write a zero byte at address 0xfffffffe.
The original problem should have been handled with an *actual* overflow check.
The only reason acpidump, which passes a stack pointer here, even *works* on 64-bit systems is because it uses the sprintf from libc.  Except the Linux [vendored version](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/tools/power/acpi/tools/acpidump?id=612c29328466bdc1454ce76959fc03a1e2f7087a) which segfaults.
=> Fix nonsensical overflow check in vsnprintf

source/common/adisasm.c, source/compiler/aslprintf.c, source/compiler/dtio.c, source/compiler/prutils.c, source/components/executer/exconvrt.c, source/components/tables/tbfind.c, source/components/utilities/utnonansi.c, source/include/acdebug.h, source/include/actbl.h, source/include/actypes.h, source/os_specific/service_layers/oslinuxtbl.c, source/tools/acpidump/apfiles.c, source/tools/acpixtract/acpixtract.c, source/tools/acpixtract/axutils.c
- Apply ACPI_NONSTRING annotations where needed[1]
- Replace deprecated strncpy()[2] with memcpy()
- Avoid sequence overread in call to strncmp()
[1] #1006 
[2] https://github.com/KSPP/linux/issues/90
=> Follow-up on ACPI_NONSTRING and strncpy() deprecation

source/components/dispatcher/dsmthdat.c, source/components/executer/extrace.c, source/include/acinterp.h
When debug level is set to `ACPI_LV_TRACE_POINT` method start and exit are emitted into the debug logs. This can be useful to understand call paths, however none of the arguments for the method calls are populated even when turning up other debug levels.
This can be useful for BIOSes that contain debug strings to see those strings. When `ACPI_LV_TRACE_POINT` is set also output all of the arguments for a given method call.
This enables this type of debugging:
```
extrace-0138 ex_trace_point        : Method Begin [0x0000000096b240c4:\M460] execution.
extrace-0173 ex_trace_args         :  "  POST CODE: %X  ACPI TIMER: %X  TIME: %d.%d ms\n", b0003f53, 1a26a8b2, 0, 15e, 0, 0
extrace-0138 ex_trace_point        : Method End [0x0000000096b240c4:\M460] execution.
```
=> Add support for printing AML arguments when trace point enabled

source/components/executer/extrace.c
Early in kernel boot pointers can't be used and so %p shows up incorrectly:
```
extrace-0138 ex_trace_point        : Method Begin [0x(____ptrval____):\M460] execution.
```
Later in the boot %p works, but it's not really actually useful when the pathname can resolve properly. Adjust the debug print so that if the Pathname resolves that the pointer isn't also printed:
```
extrace-0138 ex_trace_point        : Method Begin [\M460] execution.
```
=> Decrease `AcpiExTracePoint` verbosity

source/components/parser/psopinfo.c
Modify variable definition position to prevent potential undefined risks.
=> Modify variable position

source/components/events/evglock.c, source/include/acpixf.h
Introduce AcpiGbl_UseGlobalLock, which allows to skip the Global Lock initialization. This is useful for systems without Global Lock (such as LoongArch), so as to avoid error messages during boot phase:
ACPI Error: Could not enable GlobalLock event (20240827/evxfevnt-182)
ACPI Error: No response from Global Lock hardware, disabling lock (20240827/evglock-59)
=> ACPICA: Allow to skip Global Lock initialization

source/compiler/aslanalyze.c, source/include/actbl.h, source/os_specific/efi/osefitbl.c, source/os_specific/service_layers/oslinuxtbl.c
Add ACPI_NONSTRING for destination char arrays without a terminating NUL character. This is a follow-up to 1035a3d453f7 where a few more destination arrays were missed
Closes: #1018
=> Apply ACPI_NONSTRING

source/common/adisasm.c, source/compiler/dttemplate.c
Print informational messages to stdout as opposed to stderr.
=> iASL/Templates: Use correct fd for printing info messages

source/components/utilities/utnonansi.c
I mistakenly replaced strncpy with memcpy in commit # 83019b4, not realizing the entire context behind *why* strncpy was used. In this safer implementation of strncpy, it does not make sense to use memcpy only to null-terminate strings passed to acpi_ut_safe_strncpy one byte early. The consequences of doing so are understandably *bad*, as was evident by the kernel test bot reporting problems[1]
This PR relates to #1009 
Link: https://lore.kernel.org/all/202505081033.50e45ff4-lkp@intel.com [1]
Reported-by: kernel test robot <oliver.sang@intel.com>
Closes: https://lore.kernel.org/oe-lkp/202505081033.50e45ff4-lkp@intel.com
=> Switch back to using strncpy in acpi_ut_safe_strncpy

source/components/dispatcher/dsmethod.c
When deleting the previous walkstate operand stack AcpiDsCallControlMethod() was deleting ObjDesc->Method.ParamCount operands. But Method.ParamCount does not necessarily match ThisWalkState->NumOperands, it may be either less or more.
After correcting the for loop to check `i < ThisWalkState->NumOperands` the code is identical to AcpiDsClearOperands(), so just outright replace the code with AcpiDsClearOperands() to fix this.
=> dispatcher: Use AcpiDsClearOperands() in AcpiDsCallControlMethod()

source/include/actbl1.h
This has been renamed in more recent CXL specs (3.0+), as type3 (memory expanders) can also use HDM-DB for device coherent memory.
=> CEDT: Rename CXL Window coherency restrictions

source/tools/acpidump/apdump.c
The function ap_is_valid_checksum() has a boolean name suggesting it should return TRUE/FALSE, but incorrectly returns AE_OK on success and has no explicit return on failure, leading to undefined behavior.
Fix by returning proper values:
- FALSE when checksum validation fails
- TRUE when checksum validation succeeds
=> ACPICA: acpidump: fix return values in ap_is_valid_checksum()

source/components/namespace/nsxfname.c, source/components/utilities/utobject.c
AcpiUtCreateInternalObject may allocate memory from a slab cache via kmem_cache_zalloc, but the code currently frees it with ACPI_FREE, which calls kfree. This mismatch prevents the object from being released properly and may lead to memory leaks or other issues.
Fix this by replacing ACPI_FREE with AcpiUtDeleteObjectDesc, which matches the allocation method used for internal objects.
=> ACPICA: replace ACPI_FREE with AcpiUtDeleteObjectDesc

source/include/actypes.h
Some AMD systems have support for a C4 C-state.  This isn't directly used in acpica, but the definitions are used in Linux and should be updated in acpica as well.
=> Add definition for ACPI C4 C-state

source/common/ahids.c, source/common/ahuuids.c, source/include/acuuid.h
This patch series adds a couple of previously unknown _DSM UUIDs i encountered while compiling/decompiling ACPI tables.
Additionally this patch series adds the "PNP0C32" hardware ID to the list of known hardware IDs so that the AML disassembler can properly detect PNP0C32 devices.
=> Add new hardware IDs and _DSM UUIDs
