acpica/acpica

generate/unix/Makefile.config, generate/unix/acpidump/Makefile, source/os_specific/service_layers/osbsdtbl.c
Changes reviewed from the NetBSD team.
The proposed changes plus required #54 enable ACPICA on NetBSD.
=> Add support for NetBSD

source/include/platform/acnetbsd.h, tests/aapits/Makefile
Tested to build on NetBSD-current.
=> Resurrect aapits

source/components/dispatcher/dsmethod.c, source/components/hardware/hwpci.c
Internal bugs.
Reporter has reported that this can mute the static analysis tool.
Please check.
-Lv
=> Acpica jira

source/components/utilities/utclib.c, source/include/acutils.h, source/include/platform/acefi.h, source/include/platform/acefiex.h
Fixes for recent EFI and Clib changes.
=> Efi portable

generate/linux/make-patches.sh, source/components/events/evgpe.c, source/components/hardware/hwgpe.c, source/include/actypes.h
Patches generated in recent ACPICA release process.
=> Acpica diverg

generate/linux/libacpica.sh, source/components/hardware/hwxfsleep.c, source/components/namespace/nssearch.c, source/components/tables/tbutils.c, source/components/utilities/utxfinit.c, source/include/acclib.h, source/include/accommon.h, source/include/actypes.h, source/include/acutils.h
20150616 release fixes required by Linux.
-Lv
=> Acpica 1506

source/include/platform/acenvex.h, source/include/platform/acmsvcex.h, source/include/platform/acwinex.h
This patch fixes a regression introduced recently.
=> MSVC: Fix inclusion order issues.

generate/msvc/AcpiDump.dsp, generate/msvc/AcpiExec.dsp, generate/msvc/AcpiHelp.dsp, generate/msvc/AcpiNames.dsp, generate/msvc/AcpiSrc.dsp, generate/msvc/AcpiSubsystem.dsp, generate/msvc/AcpiXtract.dsp, generate/msvc/ApiTest.dsp, generate/msvc/AslCompiler.dsp, generate/msvc/Examples.dsp
Updated due to recent changes.
=> MSVC builds update

source/components/debugger/dbcmds.c, source/components/debugger/dbinput.c, source/components/executer/exdebug.c
Small fixes for the tracing facility.
Thanks for the review.
-Lv
=> Acpica trace fixes

generate/unix/acpiexec/Makefile, source/components/debugger/dbdisply.c, source/components/debugger/dbmethod.c, source/components/debugger/dbobject.c, source/components/debugger/dbutils.c, source/components/debugger/dbxface.c, source/components/disassembler/dmopcode.c, source/components/dispatcher/dsmethod.c, source/include/acdebug.h, source/include/acdisasm.h, source/include/aclocal.h
These commits are required to port ACPICA debugger to Linux kernel.
-Lv
=> Acpica debugger

source/common/adisasm.c, source/compiler/aslstartup.c, source/components/debugger/dbdisply.c, source/components/debugger/dbinput.c, source/components/debugger/dbmethod.c, source/components/debugger/dbnames.c, source/components/debugger/dbxface.c, source/components/disassembler/dmwalk.c, source/components/dispatcher/dsdebug.c, source/components/executer/exdump.c, source/components/namespace/nsutils.c, source/components/utilities/utmisc.c, source/components/utilities/utxface.c, source/components/utilities/utxfinit.c, source/include/acdebug.h, source/include/acglobal.h, source/include/acpixf.h, source/tools/acpiexec/aeexec.c, source/tools/acpiexec/aemain.c
Recent fixes and debugger related configurability improvements.
The debugger support is tested.
So the code here is stable.
=> Acpica debug

source/components/debugger/dbcmds.c, source/components/debugger/dbdisply.c, source/components/debugger/dbnames.c, source/components/debugger/dbtest.c, source/components/namespace/nsdump.c, source/components/namespace/nseval.c, source/components/namespace/nsinit.c, source/components/namespace/nssearch.c, source/components/utilities/utaddress.c
The fixes for the path issues.
-Lv
=> Acpica path

source/components/debugger/dbdisply.c, source/components/events/evhandler.c, source/components/events/evregion.c, source/components/events/evrgnini.c, source/components/events/evxfregn.c, source/components/executer/excreate.c, source/components/utilities/utinit.c, source/components/utilities/utxfinit.c, source/include/acevents.h, source/include/acglobal.h, source/include/aclocal.h, source/include/acobject.h, source/include/acpixf.h, source/tools/acpiexec/aecommon.h, source/tools/acpiexec/aehandlers.c, source/tools/acpiexec/aemain.c, source/tools/acpiexec/aetables.c
The rebased code on top of new committed modlevel support.
=> Acpica reg

source/components/namespace/nsconvert.c, source/components/namespace/nsrepair.c, source/include/aclocal.h, source/include/acnamesp.h
String -> Reference conversion.
=> Acpica repair

source/tools/examples/examples.c
Fix of the regression caused by the new initialization order change.
The change should also be applied to acpiexamples.
Reported by Colin Ian King.
https://bugs.acpica.org/show_bug.cgi?id=1226
=> acpica examples

source/components/hardware/hwregs.c, source/include/acmacros.h
GAS support of AccessWidth/BitOffset.
This is just a demo, used for discussion.
=> Acpica hardware

generate/linux/libacpica.sh, source/components/hardware/hwregs.c, source/include/acmacros.h, source/tools/acpisrc/astable.c
Required by Linux community.
Hope this can be merged as early as possible.
As the linuxize result of this commit is very big.
Maintaining the commits between current synced ACPICA<->Linux head and this commit will be a bandwidth consuming work.
Thanks
-Lv
=> Acpica indent

generate/linux/libacpica.sh, source/components/hardware/hwregs.c, source/include/acmacros.h, source/tools/acpisrc/astable.c
Release fixes generated during the ACPICA 20160318 release cycle.
=> Acpica 1603

source/components/executer/exfldio.c, source/components/hardware/hwregs.c, source/include/acmacros.h
Just for review purpose as the solution of BZ 1270 hasn't been determined and the patch order hasn't been fixed.
Thanks
-Lv
=> Acpica access

tests/aslts/bin/settings, tests/aslts/src/runtime/cntl/common.asl, tests/aslts/src/runtime/cntl/runmode.asl, tests/aslts/src/runtime/collections/functional/README, tests/aslts/src/runtime/collections/functional/module/DECL.asl, tests/aslts/src/runtime/collections/functional/module/MAIN.asl, tests/aslts/src/runtime/collections/functional/module/Makefile, tests/aslts/src/runtime/collections/functional/module/RUN.asl, tests/aslts/src/runtime/collections/functional/module/object.asl, tests/aslts/src/runtime/collections/functional/module/scope.asl
ASLTS changes related to the TermList parsing.
Note that the cases brought by this change can only report OK after merging the following pull request:
https://github.com/acpica/acpica/pull/134
Thanks
-Lv
=> Acpica aslts

source/include/acutils.h, source/include/platform/aclinux.h
A simple improvement required by the https://bugzilla.kernel.org/show_bug.cgi?id=117461 reporter.
Thanks
-Lv
=> Acpica print

source/compiler/aslstubs.c, source/components/dispatcher/dsopcode.c, source/components/events/evrgnini.c, source/components/executer/exconfig.c, source/components/namespace/nsload.c, source/components/namespace/nsparse.c, source/components/parser/psparse.c, source/components/parser/psxface.c, source/components/tables/tbxfload.c, source/components/utilities/utxfinit.c, source/include/acnamesp.h, source/include/acparser.h, source/include/acpixf.h, tests/aslts/src/runtime/cntl/common.asl, tests/aslts/src/runtime/collections/functional/module/RUN.asl, tests/aslts/src/runtime/collections/functional/module/object.asl, tests/aslts/src/runtime/collections/functional/module/order.asl, tests/aslts/src/runtime/collections/functional/module/scope.asl
The interpreter enhancement of TermList support for table loading.
It should be OK to merge, because the feature is protected by a global option.
We still have chance to optimize it.
Test cases about this change can be found at: https://github.com/acpica/acpica/pull/135.
Thanks
-Lv
=> Acpica parser

source/components/dispatcher/dsopcode.c, source/components/executer/exconfig.c, source/components/namespace/nsparse.c
This contains 2 fixes required by the current module level code approach.
http://bugs.acpica.org/show_bug.cgi?id=1289
http://bugs.acpica.org/show_bug.cgi?id=1279
Please check.
Thanks
-Lv
=> Acpica module

source/components/events/evgpe.c, source/components/events/evxfgpe.c, source/components/hardware/hwgpe.c, source/include/acevents.h, source/include/aclocal.h, source/include/acpixf.h, source/include/actypes.h
This contains the force disabling/enabling mechanism.
=> Acpica gpe

generate/efi/acpidump/Makefile, generate/efi/acpidump/acpidump.inf
Simple build breakage fix.
Please check.
=> Acpica efi

source/components/tables/tbfadt.c, source/components/tables/tbinstal.c, source/include/actables.h, source/include/actypes.h
This is required to fix a bug in Linux sysfs handling.
https://bugzilla.kernel.org/show_bug.cgi?id=150841
Thanks
Lv
=> Acpica sysfs

source/include/platform/acefi.h, source/include/platform/acefiex.h, source/os_specific/efi/osefixf.c
Implement AcpiOsReadPciConfiguration and AcpiOsWritePciConfiguration on efi environment to help porting the AcpiExec utility.
=> Efi PCI Configuration Space access

source/components/tables/tbfadt.c
FADT 32-bit favor mechanism is not good.
hwregs.c uses 64-bit fields.
So when 64-bit fields are zero, we need to fill it with 32-bit fields.
When 32-bit favor mode is used.
We also need to fill 64-bit fields with 32-bit fields. - we call this as 32-bit override.
But we only allow such override to happen when 32-bit "Address" doesn't match 64-bit "Address".
This brings troubles because:
When 32-bit "Address" matches 64-bit "Address", override doesn't happen, leaving us with wrong AccessSize/BitWidth/BitOffset fields.
This patch fixes this issue by performing 32-bit override under the condition: 32-bit Address is not zero. So that when 32-bit "Address" fields is not zero, all 64-bit fields are re-initialized using 32-bit register access algorithm.
Thanks
=> Acpica fadt

source/compiler/aslstubs.c, source/components/dispatcher/dsmethod.c, source/components/dispatcher/dswload2.c, source/components/events/evrgnini.c, source/components/executer/exconfig.c, source/components/executer/exoparg1.c, source/components/executer/extrace.c, source/components/executer/exutils.c, source/components/namespace/nsload.c, source/components/namespace/nsparse.c, source/components/namespace/nsutils.c, source/components/parser/psparse.c, source/components/parser/psxface.c, source/components/tables/tbdata.c, source/components/tables/tbfind.c, source/components/tables/tbxfload.c, source/components/utilities/utaddress.c, source/components/utilities/utxfinit.c, source/include/acnamesp.h, source/include/acparser.h, source/include/acpixf.h, source/include/actables.h, source/tools/acpiexec/aemain.c, tests/aslts/bin/asltsrun, tests/aslts/src/runtime/cntl/common.asl, tests/aslts/src/runtime/collections/functional/module/RUN.asl, tests/aslts/src/runtime/collections/functional/module/object.asl, tests/aslts/src/runtime/collections/functional/module/order.asl, tests/aslts/src/runtime/collections/functional/module/scope.asl
The mlc/lock fix in the order that the mlc one (not functional enabled) goes first.
So that when the coverage is not good in the lock fix, mlc needn't be reverted when the lock fix is reverted.
Thanks
Lv
=> Acpica mlc

source/components/utilities/utstrtoul64.c
Divergences generated during 20160831 release cycle.
=> Acpica 1608

source/components/executer/exconfig.c, source/components/parser/psxface.c, source/components/tables/tbdata.c, source/components/tables/tbfind.c, source/components/tables/tbxfload.c, tests/aslts/bin/asltsrun
Additional lock fix code.
Containing an urgent fix for my mistake.
=> Acpica locks

source/include/platform/acmacosx.h, source/os_specific/service_layers/osunixxf.c
=> Acpica mac

source/os_specific/service_layers/osunixxf.c
Not a perfect solution, but fixes macosx segfault issue.
=> Acpica MacOSX

generate/linux/gen-patch.sh, generate/linux/gen-repo.sh, generate/linux/make-patches.sh
Urgent fix as "release process" is found broken on newer distros.
=> Acpica script

source/compiler/aslstubs.c, source/components/dispatcher/dsinit.c, source/components/dispatcher/dsmethod.c, source/components/dispatcher/dsopcode.c, source/components/dispatcher/dswload2.c, source/components/events/evrgnini.c, source/components/executer/exconfig.c, source/components/namespace/nsload.c, source/components/tables/tbdata.c, source/components/tables/tbfadt.c, source/components/tables/tbutils.c, source/components/tables/tbxface.c, source/components/tables/tbxfload.c, source/include/acevents.h, source/include/acpixf.h, source/include/actables.h, source/include/actbl.h, source/tools/acpinames/anstubs.c
Divergences reduction.
I have tested linuxized version of this patchset.
With acpi_get_table_with_size() changed to invoked acpi_get_table(); early_acpi_os_unmap_memory() changed to invoke acpi_put_table().
Linux successfully booted, no complain can be seen.
Thanks
=> Acpica diverg table

source/compiler/aslstubs.c, source/components/dispatcher/dsinit.c, source/components/dispatcher/dsmethod.c, source/components/dispatcher/dsopcode.c, source/components/dispatcher/dswload2.c, source/components/events/evrgnini.c, source/components/namespace/nsload.c, source/include/acevents.h, source/tools/acpinames/anstubs.c
Some lock fixes and improvements.
=> Acpica lock

tests/aslts/HOW_TO_USE, tests/aslts/src/runtime/cntl/runmode.asl
=> Spelling fixes

source/common/acfileio.c
Plus a semantic change renaming ErrorExit.
I've only smoke-tested it by running this code on my laptop.
=> avoid resource leak, check for alloc failure

source/components/hardware/hwesleep.c, source/components/hardware/hwsleep.c, source/include/acexcep.h, source/include/acpiosxf.h, source/os_specific/service_layers/osunixxf.c, source/os_specific/service_layers/oswinxf.c
Reduce sleep register divergences.
=> Acpica sleep

generate/msvc/AcpiDump.dsp, generate/msvc/AcpiExec.dsp, generate/msvc/AcpiHelp.dsp, generate/msvc/AcpiNames.dsp, generate/msvc/AcpiSubsystem.dsp, generate/msvc/AslCompiler.dsp, generate/msvc/Examples.dsp, source/include/platform/acenv.h, source/os_specific/service_layers/osgendbg.c
Trivial fixes.
MSVC6 build fixes and strcpy -> strncpy change.
=> Acpica trivial

generate/linux/gen-patch.sh, generate/linux/gen-repo.sh, generate/linux/make-patches.sh, source/include/platform/aclinux.h, source/include/platform/aclinuxex.h, source/os_specific/service_layers/osunixxf.c
Divergences generated in ACPICA 201612 release cycle.
Especially, the release script still contains problems that are fixed in this pull request.
So it is urgent.
Lv
=> Acpica 1612

generate/linux/libacpica.sh, source/tools/acpisrc/astable.c
Restore ACPICA specific intel compiler settings.
=> Acpica intel

source/components/namespace/nsutils.c
Back ported community material.
=> Acpica ifdef

tests/aslts.sh, tests/aslts/Makefile.def, tests/aslts/Makefile.switch, tests/aslts/bin/Do, tests/aslts/bin/asltsdiffres, tests/aslts/bin/asltsrun, tests/aslts/bin/common, tests/aslts/bin/settings
This pull request contains changes to ASLTS test suite script to add binary comparison as well as change slack/norm modes to opt/nopt modes.
=> Aslts script

tests/aslts/Makefile.def, tests/aslts/bin/Do, tests/aslts/bin/asltsrun
This pull request contains stylistic fixes within the aslts scripts.
=> ASLTS: adding stylistic changes to testsuite script

source/compiler/asltree.c, source/compiler/cvcompiler.c, source/compiler/cvdisasm.c, source/compiler/cvparser.c
This fixes coverity errors caused by the converter merge.
=> Coverity fix001

source/include/actbl1.h
=> Tables: Fix defined values for MADT PCAT_COMPAT flag

tests/aslts.sh
=> ASLTS: Fixing small syntax issue resulting in ASLTS build issues

source/components/events/evxfevnt.c
Runtime support of reduced hardware.
=> Acpica reduced

source/components/utilities/utownerid.c
=> Add explanation for UINT32 casts

tests/aslts/bin/settings, tests/aslts/src/runtime/cntl/common.asl, tests/aslts/src/runtime/collections/functional/Makefile, tests/aslts/src/runtime/collections/functional/external/DECL.asl, tests/aslts/src/runtime/collections/functional/external/MAIN.asl, tests/aslts/src/runtime/collections/functional/external/Makefile, tests/aslts/src/runtime/collections/functional/external/RUN.asl, tests/aslts/src/runtime/collections/functional/external/external.asl
This pull request adds tests for external declarations. This is a simple test that is meant ensure that external declarations are being resolved to the proper type.
=> Aslts external tests01

source/compiler/aslload.c, tests/aslts/src/runtime/collections/functional/external/MAIN.asl
This pull request fixes a corner case for compiling externals that refer to Field Units.
=> External op refactor07

tests/misc/converterSample.asl
=> ASLTS: misc: adding ASL/ASL+ converter sample

source/common/acfileio.c, source/common/adisasm.c, source/include/acapps.h, source/tools/acpiexec/aemain.c, source/tools/acpinames/anmain.c
=> Tools: Deallocate memory allocated by AcGetAllTablesFromFile

source/components/tables/tbdata.c, source/components/tables/tbinstal.c, source/components/tables/tbutils.c, source/components/tables/tbxface.c, source/components/tables/tbxfload.c, source/include/acpixf.h, source/include/actables.h, source/include/actbl.h
Similar as #121, but no ASLTS change.
=> Acpica tables2

source/components/tables/tbdata.c, source/components/tables/tbxface.c
Need one more commit to enable the new mechanism.
=> Acpica tables

tests/aslts.sh, tests/aslts/Makefile.def, tests/aslts/Makefile.switch, tests/aslts/bin/Do, tests/aslts/bin/common
General clean up for Makefiles and bash scripts.
=> ASLTS script clean up

source/components/dispatcher/dscontrol.c, source/components/utilities/utinit.c, source/include/acconfig.h, source/include/aclocal.h, source/include/acpixf.h, source/include/actypes.h, source/tools/acpiexec/aemain.c
=> Acpica loop

source/compiler/aslerror.c
=> iASL: adding extra check to avoid NULL dereference of SourceFile

source/compiler/aslerror.c
by indenting the suberror message, it helps users distinguish iASL
error output between errors and sub-errors.
=> iASL: trivial style fixes and indent suberror message when printed

source/components/utilities/utmath.c
=> Acpica style

source/components/utilities/utnonansi.c, source/include/acutils.h
=> Utilities: fixing if def macro to avoid build errors

source/compiler/dtcompile.c, source/compiler/dtcompiler.h, source/compiler/dtexpress.c, source/compiler/dtparser.l, source/compiler/dtparser.y, source/compiler/dttable.c, source/compiler/dttable1.c, source/compiler/dttable2.c
=> Simple adjustments for data table compiler

source/tools/acpiexec/aemain.c, source/tools/acpiexec/aetables.c
Acpiexec fixes around GPE initialization order and register coverage.
=> Gpe acpiexec

source/tools/acpisrc/acpisrc.h, source/tools/acpisrc/asconvrt.c, source/tools/acpisrc/asfile.c, source/tools/acpisrc/astable.c, source/tools/acpisrc/asutils.c
=> acpisrc: adding feature to convert files with SPDX headers

tests/aslts/src/runtime/collections/functional/table/load.asl, tests/aslts/src/runtime/collections/functional/table/ssdt6.asl
=> ASLTS: adding package resolution with table load testing

source/components/parser/psloop.c
The dispatcher and the executer process the parse nodes During table
load. Error status from the evaluation confuses the AML parser. This
results in the parser failing to complete parsing of the current
scope op which becomes problematic. For the incorrect AML below, _ADR
never gets created.
DefinitionBlock(...)
{
Scope (\_SB)
{
Device (PCI0){...}
Name (OBJ1, 0x0)
OBJ1 = PCI0 + 5 // Results in an operand error.
} // \_SB not closed
// parser looks for \_SB._SB.PCI0, results in AE_NOT_FOUND error
// Entire scope block gets skipped.
Scope (\_SB.PCI0)
{
Name (_ADR, 0x0)
}
}
This patch fixes the above error by properly completing the initial
\_SB scope after an error by clearing errors that occur during table
load. In the above case, this means that OBJ1 = PIC0 + 5 is skipped.
Link: …
=> AML Parser: ignore dispatcher error status during table load

source/components/utilities/utdelete.c
=> Reference count: add additional debugging details

generate/unix/iasl/Makefile
=> iASL: Makefile: support parent directories with spaces

source/compiler/aslcompile.c, tests/aslts/src/runtime/collections/Identity2MS/abbu/Makefile, tests/aslts/src/runtime/collections/bdemo/ACPICA/bdemo/Makefile, tests/aslts/src/runtime/collections/complex/misc/Makefile, tests/aslts/src/runtime/collections/complex/namespace/Makefile, tests/aslts/src/runtime/collections/complex/operand/tests/oarg/Makefile, tests/aslts/src/runtime/collections/complex/operand/tests/oconst/Makefile, tests/aslts/src/runtime/collections/complex/operand/tests/olocal/Makefile, tests/aslts/src/runtime/collections/complex/operand/tests/onamedglob/Makefile, tests/aslts/src/runtime/collections/complex/operand/tests/onamedloc/Makefile, tests/aslts/src/runtime/collections/complex/operand/tests/opackageel/Makefile, tests/aslts/src/runtime/collections/complex/operand/tests/oreftonamed/Makefile, tests/aslts/src/runtime/collections/complex/operand/tests/oreftopackageel/Makefile, tests/aslts/src/runtime/collections/complex/operand/tests/oreturn/Makefile, tests/aslts/src/runtime/collections/complex/result/tests/rcopyobject/Makefile, tests/aslts/src/runtime/collections/complex/result/tests/rexplicitconv/Makefile, tests/aslts/src/runtime/collections/complex/result/tests/rindecrement/Makefile, tests/aslts/src/runtime/collections/complex/result/tests/roptional/Makefile, tests/aslts/src/runtime/collections/complex/result/tests/rstore/Makefile, tests/aslts/src/runtime/collections/exceptions/exc_operand/exc_operand2/Makefile, tests/aslts/src/runtime/collections/exceptions/exc_ref/Makefile, tests/aslts/src/runtime/collections/exceptions/exc_result/exc_result2/Makefile, tests/aslts/src/runtime/collections/exceptions/exc_tbl/Makefile, tests/aslts/src/runtime/collections/functional/control/Makefile, tests/aslts/src/runtime/collections/functional/name/Makefile, tests/aslts/src/runtime/collections/functional/reference/Makefile, tests/aslts/src/runtime/collections/functional/region/Makefile, tests/aslts/src/runtime/collections/functional/synchronization/Makefile, tests/aslts/src/runtime/collections/functional/table/Makefile, tests/aslts/src/runtime/collections/service/condbranches/Makefile
iASL fix and ASLTS changes resulting from enhanced cross reference analysis
=> Xref error

source/components/dispatcher/dsfield.c, tests/aslts/src/runtime/collections/functional/region/regionfield.asl
=> PCC operation region: fix if statement by correctly checking the SpaceId

source/compiler/asldefine.h
=> iASL: update supported ACPI specification revision

source/compiler/aslload.c, source/compiler/aslxref.c
This pull request makes changes to 1.) detect forward references for field declarations at root scope and 2.) implements forward reference detection inside of scopes.
=> Improve forward reference detection

source/compiler/dtcompilerparser.l
=> iASL: fix data table patterns

generate/unix/Makefile.config, source/compiler/aslmain.c, source/compiler/aslstartup.c, source/compiler/asltypes.h, source/compiler/aslutils.c, source/compiler/dtcompile.c
This pull request adds support to compile data tables and ASL files in a single command
=> multiple data table and ASL file compilation

source/compiler/dtcompilerparser.l, tests/aslts.sh
=> ASLTS: add option to only execute data table compiler tests

source/common/dmtbdump3.c, source/compiler/aslmessages.c, source/compiler/aslmessages.h, source/compiler/dtcompile.c
=> iASL: DT: detect invalid field labels

source/components/debugger/dbinput.c, source/components/debugger/dbnames.c, source/components/dispatcher/dsfield.c, source/tools/acpiexec/aecommon.h, source/tools/acpiexec/aeinitfile.c, source/tools/acpiexec/aemain.c
=> add support for simple types and field units in InitFile

source/tools/acpisrc/astable.c
=> Acpisrc: add ACPI_REGION_WALK_INFO for linuxization

source/compiler/aslcompiler.y, source/compiler/dtcompiler.h, source/components/debugger/dbnames.c, source/include/platform/acenv.h, source/tools/acpinames/anstubs.c, source/tools/acpisrc/asmain.c
=> acpisrc: add unix line ending support for non-windows build

source/compiler/asltransform.c
=> iASL: enhance duplicate case detection for buffers

source/compiler/aslload.c
=> iASL: improve forward reference detection for method calls

generate/msvc2017/AslCompiler.vcxproj
This pull request contains changes to add dependencies to aslparser.y and add build rules for debug mode
=> Msvc 2017 build file fixes

source/compiler/aslmessages.c, source/compiler/aslmessages.h, source/compiler/aslmethod.c
=> iASL: check method numArgs against length of method parameter list

source/compiler/aslmessages.c, source/compiler/aslmessages.h, source/compiler/aslmethod.c
Signed-off-by: ignacio ramirez piriz <t-igra@microsoft.com>
[ ek several code changes ]
=> iASL: warn on static operation region declared in methods

source/compiler/aslmethod.c, source/compiler/aslrules.y
This pull request changes the parse tree of return type and parameter type lists and extracts functions that can be used to process them.
=> iasl: refactor method analysis

source/compiler/aslexternal.c
=> iASL: fix method parameter type list processing in external declarations

source/compiler/dtutils.c
=> iASL: DT: fix segfault on errors that aren't associated with a field

generate/msvc2017/readme.txt
This file is a updated version of the readme file in the msvc9
directory that was deleted with the removal of old visual studio
files.
=> Add directions on ACPICA generation using msvc2017

source/include/actypes.h
Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
=> Drop the repeated word "an" in a comment.

source/compiler/aslload.c
=> iASL: save target type and possible method parameters for Alias objects

tests/aslts.sh
unnecessary 2 tabs at end of line removed
=> tests/aslts.sh: Remove unnecessary tabs at end of line

generate/release/build.sh
unnecessary  2 tabs at end of line removed
=> generate/release/build.sh: Remove tabs at end of line

generate/release/release.sh
unnecessary tabs at end of lines removed
=> generate/release/release.sh: Remove tabs at end of lines

source/compiler/aslallocate.c, source/compiler/aslascii.c
Signed-off-by: Elyes HAOUAS <ehaouas@noos.fr>
=> Fix some typos

source/include/acoutput.h
s/optimzation/optimization/
Signed-off-by: Bhaskar Chowdhury <unixbhaskar@gmail.com>
=> Fix a typo

source/include/actbl1.h
This pull request adds a new sub table along with several defines
=> Add more structs to CEDT table  

source/components/utilities/utosi.c, source/include/actypes.h
See: https://github.com/MicrosoftDocs/windows-driver-docs/commit/5164e24985e78ef4870d7a5801a5336104f36366
=> Add support for Windows 2020 _OSI string

tests/aslts/src/runtime/collections/mt/mutex/mxs.asl, tests/aslts/src/runtime/collections/mt/mutex/tests.asl
Signed-off-by: Elyes HAOUAS <ehaouas@noos.fr>
=> Fix spelling errors

source/components/utilities/utosi.c, source/include/actypes.h
See https://github.com/MicrosoftDocs/windows-driver-docs/commit/a061e31fd77c20cc8e6eb0234e5d3a83e417f48
=> Add support for the Windows 11 _OSI string

source/components/executer/exsystem.c
Signed-off-by: Selvarasu Ganesan <selvarasu.ganesan@arm.com>
=> executer/exsystem: Fix some typo mistakes

source/common/dmtbinfo3.c
Signed-off-by: Kuppuswamy Sathyanarayanan <sathyanarayanan.kuppuswamy@linux.intel.com>
=> iASL: Add CCEL table to both compiler/disassembler

source/compiler/dttable2.c
Since those fields are optional some combinations of them were causing
unpredicted flow when compiling the table.
=> iASL: NHLT: Fix compilation of optional undocumented fields

source/include/actbl2.h
Fixes #783 
I believe this is what @OS4User was talking about...
=> Fix typo as per Issue #783

source/components/utilities/utcksum.c
Signed-off-by: Elyes Haouas <ehaouas@noos.fr>
=> Remove trailing whitespace

source/components/debugger/dbstats.c, source/components/utilities/utdebug.c, source/components/utilities/utinit.c, source/include/acglobal.h, source/include/actypes.h, source/include/platform/aclinux.h
Fixes #771
Details are in the commit messages.
=> Fix dangling pointer warning for AcpiUtInitStackPtrTrace

source/include/actbl2.h
=> Revert "Headers: Replace zero-length array with flexible-array member"

source/include/platform/achaiku.h
Signed-off-by: Elyes Haouas <ehaouas@noos.fr>
=> Remove extern prototypes in achaiku.h file

source/compiler/aslbtypes.c, source/compiler/aslparseop.c, source/compiler/asltree.c, source/compiler/dtexpress.c
Signed-off-by: Elyes Haouas <ehaouas@noos.fr>
=> Use ACPI_GET_FUNCTION_NAME

source/common/dmextern.c, source/compiler/aslrestype2s.c, source/tools/acpisrc/asconvrt.c
This fixes build with Clang 15 and later.  Please see Issue #849.
=> Remove write-only variables

zephyr/module.yml
add module name for Zephyr build system
=> build: add module name for build system

source/include/actbl1.h
Add upstream port and any port definitions for SSLBIS.
=> Add port definitions for CDAT SSLBIS

source/os_specific/service_layers/oszephyr.c
Two fixes without which Zephyr doesn't fully work.
=> osal: Zephyr: A couple of important fixes

tests/aslts/src/runtime/cntl/common.asl
NRMT is initialized as "", which is a zero-length string. Trying to Store a longer string to it works on ACPICA, however, is incompatible with other implementations like Acpi.sys, which doesn't allow resizing existing buffers with Store. Therefore any Store operation to it produces the same result on those implementations.
Use CopyObject to avoid any possible behavior differences.
This makes a difference on [my implementation](https://github.com/UltraOS/uACPI) (which tries to follow NT closer than ACPICA)
Without this change:
<details markdown="1"><summary>Output</summary>
```
[uACPI][INFO] [AML DEBUG] String => "64-bit mode"
[uACPI][INFO] [AML DEBUG] String => "Release of parent ACPICA code 0x1"
[uACPI][INFO] [AML DEBUG] String => "Release of ASLTS test suite  0x16"
[uACPI][INFO] [AML …
```
=> tests/common: use CopyObject instead of Store for NRMT

source/components/utilities/utosi.c, source/include/actypes.h
See: https://github.com/MicrosoftDocs/windows-driver-docs/commit/be9d1c211adf8fabe5a43de71c034b1b6d7372de
=> Add support for Windows 11 22H2 _OSI string

source/components/resources/rsaddr.c, source/components/resources/rscalc.c, source/components/resources/rslist.c, source/components/utilities/utresrc.c, source/include/amlresrc.h
Please see commit message.
Closes #446.
=> Apply pack(1) to AML_RESOURCE

LICENSE
Addresses Issue #986
/cc @SaketADumbre
=> Add a LICENSE file for ACPICA
